// Code generated by ent, DO NOT EDIT.

package catalogaccesspolicy

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the catalogaccesspolicy type in the database.
	Label = "catalog_access_policy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCatalogID holds the string denoting the catalog_id field in the database.
	FieldCatalogID = "catalog_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldExternalSystem holds the string denoting the external_system field in the database.
	FieldExternalSystem = "external_system"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldDurationField holds the string denoting the duration_field field in the database.
	FieldDurationField = "duration_field"
	// FieldDurationOptions holds the string denoting the duration_options field in the database.
	FieldDurationOptions = "duration_options"
	// EdgeCatalog holds the string denoting the catalog edge name in mutations.
	EdgeCatalog = "catalog"
	// Table holds the table name of the catalogaccesspolicy in the database.
	Table = "catalog_access_policies"
	// CatalogTable is the table that holds the catalog relation/edge.
	CatalogTable = "catalog_access_policies"
	// CatalogInverseTable is the table name for the ServiceCatalog entity.
	// It exists in this package in order to avoid circular dependency with the "servicecatalog" package.
	CatalogInverseTable = "service_catalogs"
	// CatalogColumn is the table column denoting the catalog relation/edge.
	CatalogColumn = "catalog_id"
)

// Columns holds all SQL columns for catalogaccesspolicy fields.
var Columns = []string{
	FieldID,
	FieldCatalogID,
	FieldVersion,
	FieldProvider,
	FieldExternalSystem,
	FieldGroupID,
	FieldDurationField,
	FieldDurationOptions,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CatalogIDValidator is a validator for the "catalog_id" field. It is called by the builders before save.
	CatalogIDValidator func(int) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// VersionValidator is a validator for the "version" field. It is called by the builders before save.
	VersionValidator func(int) error
	// ExternalSystemValidator is a validator for the "external_system" field. It is called by the builders before save.
	ExternalSystemValidator func(string) error
	// GroupIDValidator is a validator for the "group_id" field. It is called by the builders before save.
	GroupIDValidator func(string) error
	// DurationFieldValidator is a validator for the "duration_field" field. It is called by the builders before save.
	DurationFieldValidator func(string) error
)

// Provider defines the type for the "provider" enum field.
type Provider string

// Provider values.
const (
	ProviderGraph Provider = "graph"
)

func (pr Provider) String() string {
	return string(pr)
}

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr Provider) error {
	switch pr {
	case ProviderGraph:
		return nil
	default:
		return fmt.Errorf("catalogaccesspolicy: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the CatalogAccessPolicy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCatalogID orders the results by the catalog_id field.
func ByCatalogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByExternalSystem orders the results by the external_system field.
func ByExternalSystem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExternalSystem, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByDurationField orders the results by the duration_field field.
func ByDurationField(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationField, opts...).ToFunc()
}

// ByCatalogField orders the results by catalog field.
func ByCatalogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCatalogStep(), sql.OrderByField(field, opts...))
	}
}
func newCatalogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CatalogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CatalogTable, CatalogColumn),
	)
}
