// Code generated by ent, DO NOT EDIT.

package intakerequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the intakerequest type in the database.
	Label = "intake_request"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldOperation holds the string denoting the operation field in the database.
	FieldOperation = "operation"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldRequestDigest holds the string denoting the request_digest field in the database.
	FieldRequestDigest = "request_digest"
	// FieldDigestVersion holds the string denoting the digest_version field in the database.
	FieldDigestVersion = "digest_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldWorkItemID holds the string denoting the work_item_id field in the database.
	FieldWorkItemID = "work_item_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// Table holds the table name of the intakerequest in the database.
	Table = "intake_requests"
)

// Columns holds all SQL columns for intakerequest fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldActorID,
	FieldChannel,
	FieldOperation,
	FieldIdempotencyKey,
	FieldRequestDigest,
	FieldDigestVersion,
	FieldStatus,
	FieldWorkItemID,
	FieldCreatedAt,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(int) error
	// ActorIDValidator is a validator for the "actor_id" field. It is called by the builders before save.
	ActorIDValidator func(int) error
	// ChannelValidator is a validator for the "channel" field. It is called by the builders before save.
	ChannelValidator func(string) error
	// OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	OperationValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// RequestDigestValidator is a validator for the "request_digest" field. It is called by the builders before save.
	RequestDigestValidator func(string) error
	// DigestVersionValidator is a validator for the "digest_version" field. It is called by the builders before save.
	DigestVersionValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// WorkItemIDValidator is a validator for the "work_item_id" field. It is called by the builders before save.
	WorkItemIDValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the IntakeRequest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByOperation orders the results by the operation field.
func ByOperation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperation, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByRequestDigest orders the results by the request_digest field.
func ByRequestDigest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestDigest, opts...).ToFunc()
}

// ByDigestVersion orders the results by the digest_version field.
func ByDigestVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDigestVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByWorkItemID orders the results by the work_item_id field.
func ByWorkItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkItemID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}
