// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/configurationitem"
	"itsm-backend/ent/incident"
	"itsm-backend/ent/incidentalert"
	"itsm-backend/ent/incidentevent"
	"itsm-backend/ent/incidentmetric"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/problem"
	"itsm-backend/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// IncidentUpdate is the builder for updating Incident entities.
type IncidentUpdate struct {
	config
	hooks    []Hook
	mutation *IncidentMutation
}

// Where appends a list predicates to the IncidentUpdate builder.
func (_u *IncidentUpdate) Where(ps ...predicate.Incident) *IncidentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetType sets the "type" field.
func (_u *IncidentUpdate) SetType(v string) *IncidentUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableType(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *IncidentUpdate) SetSeverity(v string) *IncidentUpdate {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableSeverity(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetImpact sets the "impact" field.
func (_u *IncidentUpdate) SetImpact(v string) *IncidentUpdate {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableImpact(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// SetUrgency sets the "urgency" field.
func (_u *IncidentUpdate) SetUrgency(v string) *IncidentUpdate {
	_u.mutation.SetUrgency(v)
	return _u
}

// SetNillableUrgency sets the "urgency" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableUrgency(v *string) *IncidentUpdate {
	if v != nil {
		_u.SetUrgency(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *IncidentUpdate) SetWorkItemID(v int) *IncidentUpdate {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableWorkItemID(v *int) *IncidentUpdate {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetConfigurationItemID sets the "configuration_item_id" field.
func (_u *IncidentUpdate) SetConfigurationItemID(v int) *IncidentUpdate {
	_u.mutation.ResetConfigurationItemID()
	_u.mutation.SetConfigurationItemID(v)
	return _u
}

// SetNillableConfigurationItemID sets the "configuration_item_id" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableConfigurationItemID(v *int) *IncidentUpdate {
	if v != nil {
		_u.SetConfigurationItemID(*v)
	}
	return _u
}

// AddConfigurationItemID adds value to the "configuration_item_id" field.
func (_u *IncidentUpdate) AddConfigurationItemID(v int) *IncidentUpdate {
	_u.mutation.AddConfigurationItemID(v)
	return _u
}

// ClearConfigurationItemID clears the value of the "configuration_item_id" field.
func (_u *IncidentUpdate) ClearConfigurationItemID() *IncidentUpdate {
	_u.mutation.ClearConfigurationItemID()
	return _u
}

// SetImpactAnalysis sets the "impact_analysis" field.
func (_u *IncidentUpdate) SetImpactAnalysis(v map[string]interface{}) *IncidentUpdate {
	_u.mutation.SetImpactAnalysis(v)
	return _u
}

// ClearImpactAnalysis clears the value of the "impact_analysis" field.
func (_u *IncidentUpdate) ClearImpactAnalysis() *IncidentUpdate {
	_u.mutation.ClearImpactAnalysis()
	return _u
}

// SetRootCause sets the "root_cause" field.
func (_u *IncidentUpdate) SetRootCause(v map[string]interface{}) *IncidentUpdate {
	_u.mutation.SetRootCause(v)
	return _u
}

// ClearRootCause clears the value of the "root_cause" field.
func (_u *IncidentUpdate) ClearRootCause() *IncidentUpdate {
	_u.mutation.ClearRootCause()
	return _u
}

// SetResolutionSteps sets the "resolution_steps" field.
func (_u *IncidentUpdate) SetResolutionSteps(v []map[string]interface{}) *IncidentUpdate {
	_u.mutation.SetResolutionSteps(v)
	return _u
}

// AppendResolutionSteps appends value to the "resolution_steps" field.
func (_u *IncidentUpdate) AppendResolutionSteps(v []map[string]interface{}) *IncidentUpdate {
	_u.mutation.AppendResolutionSteps(v)
	return _u
}

// ClearResolutionSteps clears the value of the "resolution_steps" field.
func (_u *IncidentUpdate) ClearResolutionSteps() *IncidentUpdate {
	_u.mutation.ClearResolutionSteps()
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *IncidentUpdate) SetDetectedAt(v time.Time) *IncidentUpdate {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableDetectedAt(v *time.Time) *IncidentUpdate {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// SetEscalatedAt sets the "escalated_at" field.
func (_u *IncidentUpdate) SetEscalatedAt(v time.Time) *IncidentUpdate {
	_u.mutation.SetEscalatedAt(v)
	return _u
}

// SetNillableEscalatedAt sets the "escalated_at" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableEscalatedAt(v *time.Time) *IncidentUpdate {
	if v != nil {
		_u.SetEscalatedAt(*v)
	}
	return _u
}

// ClearEscalatedAt clears the value of the "escalated_at" field.
func (_u *IncidentUpdate) ClearEscalatedAt() *IncidentUpdate {
	_u.mutation.ClearEscalatedAt()
	return _u
}

// SetEscalationLevel sets the "escalation_level" field.
func (_u *IncidentUpdate) SetEscalationLevel(v int) *IncidentUpdate {
	_u.mutation.ResetEscalationLevel()
	_u.mutation.SetEscalationLevel(v)
	return _u
}

// SetNillableEscalationLevel sets the "escalation_level" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableEscalationLevel(v *int) *IncidentUpdate {
	if v != nil {
		_u.SetEscalationLevel(*v)
	}
	return _u
}

// AddEscalationLevel adds value to the "escalation_level" field.
func (_u *IncidentUpdate) AddEscalationLevel(v int) *IncidentUpdate {
	_u.mutation.AddEscalationLevel(v)
	return _u
}

// SetIsAutomated sets the "is_automated" field.
func (_u *IncidentUpdate) SetIsAutomated(v bool) *IncidentUpdate {
	_u.mutation.SetIsAutomated(v)
	return _u
}

// SetNillableIsAutomated sets the "is_automated" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableIsAutomated(v *bool) *IncidentUpdate {
	if v != nil {
		_u.SetIsAutomated(*v)
	}
	return _u
}

// SetIsMajorIncident sets the "is_major_incident" field.
func (_u *IncidentUpdate) SetIsMajorIncident(v bool) *IncidentUpdate {
	_u.mutation.SetIsMajorIncident(v)
	return _u
}

// SetNillableIsMajorIncident sets the "is_major_incident" field if the given value is not nil.
func (_u *IncidentUpdate) SetNillableIsMajorIncident(v *bool) *IncidentUpdate {
	if v != nil {
		_u.SetIsMajorIncident(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *IncidentUpdate) SetMetadata(v map[string]interface{}) *IncidentUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *IncidentUpdate) ClearMetadata() *IncidentUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWorkItem sets the "work_item" edge to the Ticket entity.
func (_u *IncidentUpdate) SetWorkItem(v *Ticket) *IncidentUpdate {
	return _u.SetWorkItemID(v.ID)
}

// AddRelatedIncidentIDs adds the "related_incidents" edge to the Incident entity by IDs.
func (_u *IncidentUpdate) AddRelatedIncidentIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddRelatedIncidentIDs(ids...)
	return _u
}

// AddRelatedIncidents adds the "related_incidents" edges to the Incident entity.
func (_u *IncidentUpdate) AddRelatedIncidents(v ...*Incident) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelatedIncidentIDs(ids...)
}

// AddIncidentEventIDs adds the "incident_events" edge to the IncidentEvent entity by IDs.
func (_u *IncidentUpdate) AddIncidentEventIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddIncidentEventIDs(ids...)
	return _u
}

// AddIncidentEvents adds the "incident_events" edges to the IncidentEvent entity.
func (_u *IncidentUpdate) AddIncidentEvents(v ...*IncidentEvent) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentEventIDs(ids...)
}

// AddIncidentAlertIDs adds the "incident_alerts" edge to the IncidentAlert entity by IDs.
func (_u *IncidentUpdate) AddIncidentAlertIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddIncidentAlertIDs(ids...)
	return _u
}

// AddIncidentAlerts adds the "incident_alerts" edges to the IncidentAlert entity.
func (_u *IncidentUpdate) AddIncidentAlerts(v ...*IncidentAlert) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentAlertIDs(ids...)
}

// AddIncidentMetricIDs adds the "incident_metrics" edge to the IncidentMetric entity by IDs.
func (_u *IncidentUpdate) AddIncidentMetricIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddIncidentMetricIDs(ids...)
	return _u
}

// AddIncidentMetrics adds the "incident_metrics" edges to the IncidentMetric entity.
func (_u *IncidentUpdate) AddIncidentMetrics(v ...*IncidentMetric) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentMetricIDs(ids...)
}

// AddParentIncidentIDs adds the "parent_incident" edge to the Incident entity by IDs.
func (_u *IncidentUpdate) AddParentIncidentIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddParentIncidentIDs(ids...)
	return _u
}

// AddParentIncident adds the "parent_incident" edges to the Incident entity.
func (_u *IncidentUpdate) AddParentIncident(v ...*Incident) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentIncidentIDs(ids...)
}

// AddConfigurationItemIDs adds the "configuration_items" edge to the ConfigurationItem entity by IDs.
func (_u *IncidentUpdate) AddConfigurationItemIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddConfigurationItemIDs(ids...)
	return _u
}

// AddConfigurationItems adds the "configuration_items" edges to the ConfigurationItem entity.
func (_u *IncidentUpdate) AddConfigurationItems(v ...*ConfigurationItem) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigurationItemIDs(ids...)
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (_u *IncidentUpdate) AddProblemIDs(ids ...int) *IncidentUpdate {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblems adds the "problems" edges to the Problem entity.
func (_u *IncidentUpdate) AddProblems(v ...*Problem) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_u *IncidentUpdate) Mutation() *IncidentMutation {
	return _u.mutation
}

// ClearWorkItem clears the "work_item" edge to the Ticket entity.
func (_u *IncidentUpdate) ClearWorkItem() *IncidentUpdate {
	_u.mutation.ClearWorkItem()
	return _u
}

// ClearRelatedIncidents clears all "related_incidents" edges to the Incident entity.
func (_u *IncidentUpdate) ClearRelatedIncidents() *IncidentUpdate {
	_u.mutation.ClearRelatedIncidents()
	return _u
}

// RemoveRelatedIncidentIDs removes the "related_incidents" edge to Incident entities by IDs.
func (_u *IncidentUpdate) RemoveRelatedIncidentIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveRelatedIncidentIDs(ids...)
	return _u
}

// RemoveRelatedIncidents removes "related_incidents" edges to Incident entities.
func (_u *IncidentUpdate) RemoveRelatedIncidents(v ...*Incident) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelatedIncidentIDs(ids...)
}

// ClearIncidentEvents clears all "incident_events" edges to the IncidentEvent entity.
func (_u *IncidentUpdate) ClearIncidentEvents() *IncidentUpdate {
	_u.mutation.ClearIncidentEvents()
	return _u
}

// RemoveIncidentEventIDs removes the "incident_events" edge to IncidentEvent entities by IDs.
func (_u *IncidentUpdate) RemoveIncidentEventIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveIncidentEventIDs(ids...)
	return _u
}

// RemoveIncidentEvents removes "incident_events" edges to IncidentEvent entities.
func (_u *IncidentUpdate) RemoveIncidentEvents(v ...*IncidentEvent) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentEventIDs(ids...)
}

// ClearIncidentAlerts clears all "incident_alerts" edges to the IncidentAlert entity.
func (_u *IncidentUpdate) ClearIncidentAlerts() *IncidentUpdate {
	_u.mutation.ClearIncidentAlerts()
	return _u
}

// RemoveIncidentAlertIDs removes the "incident_alerts" edge to IncidentAlert entities by IDs.
func (_u *IncidentUpdate) RemoveIncidentAlertIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveIncidentAlertIDs(ids...)
	return _u
}

// RemoveIncidentAlerts removes "incident_alerts" edges to IncidentAlert entities.
func (_u *IncidentUpdate) RemoveIncidentAlerts(v ...*IncidentAlert) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentAlertIDs(ids...)
}

// ClearIncidentMetrics clears all "incident_metrics" edges to the IncidentMetric entity.
func (_u *IncidentUpdate) ClearIncidentMetrics() *IncidentUpdate {
	_u.mutation.ClearIncidentMetrics()
	return _u
}

// RemoveIncidentMetricIDs removes the "incident_metrics" edge to IncidentMetric entities by IDs.
func (_u *IncidentUpdate) RemoveIncidentMetricIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveIncidentMetricIDs(ids...)
	return _u
}

// RemoveIncidentMetrics removes "incident_metrics" edges to IncidentMetric entities.
func (_u *IncidentUpdate) RemoveIncidentMetrics(v ...*IncidentMetric) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentMetricIDs(ids...)
}

// ClearParentIncident clears all "parent_incident" edges to the Incident entity.
func (_u *IncidentUpdate) ClearParentIncident() *IncidentUpdate {
	_u.mutation.ClearParentIncident()
	return _u
}

// RemoveParentIncidentIDs removes the "parent_incident" edge to Incident entities by IDs.
func (_u *IncidentUpdate) RemoveParentIncidentIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveParentIncidentIDs(ids...)
	return _u
}

// RemoveParentIncident removes "parent_incident" edges to Incident entities.
func (_u *IncidentUpdate) RemoveParentIncident(v ...*Incident) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentIncidentIDs(ids...)
}

// ClearConfigurationItems clears all "configuration_items" edges to the ConfigurationItem entity.
func (_u *IncidentUpdate) ClearConfigurationItems() *IncidentUpdate {
	_u.mutation.ClearConfigurationItems()
	return _u
}

// RemoveConfigurationItemIDs removes the "configuration_items" edge to ConfigurationItem entities by IDs.
func (_u *IncidentUpdate) RemoveConfigurationItemIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveConfigurationItemIDs(ids...)
	return _u
}

// RemoveConfigurationItems removes "configuration_items" edges to ConfigurationItem entities.
func (_u *IncidentUpdate) RemoveConfigurationItems(v ...*ConfigurationItem) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigurationItemIDs(ids...)
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (_u *IncidentUpdate) ClearProblems() *IncidentUpdate {
	_u.mutation.ClearProblems()
	return _u
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (_u *IncidentUpdate) RemoveProblemIDs(ids ...int) *IncidentUpdate {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblems removes "problems" edges to Problem entities.
func (_u *IncidentUpdate) RemoveProblems(v ...*Problem) *IncidentUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IncidentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IncidentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IncidentUpdate) check() error {
	if v, ok := _u.mutation.Impact(); ok {
		if err := incident.ImpactValidator(v); err != nil {
			return &ValidationError{Name: "impact", err: fmt.Errorf(`ent: validator failed for field "Incident.impact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Urgency(); ok {
		if err := incident.UrgencyValidator(v); err != nil {
			return &ValidationError{Name: "urgency", err: fmt.Errorf(`ent: validator failed for field "Incident.urgency": %w`, err)}
		}
	}
	if _u.mutation.WorkItemCleared() && len(_u.mutation.WorkItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Incident.work_item"`)
	}
	return nil
}

func (_u *IncidentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(incident.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(incident.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(incident.FieldImpact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgency(); ok {
		_spec.SetField(incident.FieldUrgency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigurationItemID(); ok {
		_spec.SetField(incident.FieldConfigurationItemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigurationItemID(); ok {
		_spec.AddField(incident.FieldConfigurationItemID, field.TypeInt, value)
	}
	if _u.mutation.ConfigurationItemIDCleared() {
		_spec.ClearField(incident.FieldConfigurationItemID, field.TypeInt)
	}
	if value, ok := _u.mutation.ImpactAnalysis(); ok {
		_spec.SetField(incident.FieldImpactAnalysis, field.TypeJSON, value)
	}
	if _u.mutation.ImpactAnalysisCleared() {
		_spec.ClearField(incident.FieldImpactAnalysis, field.TypeJSON)
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(incident.FieldRootCause, field.TypeJSON, value)
	}
	if _u.mutation.RootCauseCleared() {
		_spec.ClearField(incident.FieldRootCause, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResolutionSteps(); ok {
		_spec.SetField(incident.FieldResolutionSteps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResolutionSteps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldResolutionSteps, value)
		})
	}
	if _u.mutation.ResolutionStepsCleared() {
		_spec.ClearField(incident.FieldResolutionSteps, field.TypeJSON)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(incident.FieldDetectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EscalatedAt(); ok {
		_spec.SetField(incident.FieldEscalatedAt, field.TypeTime, value)
	}
	if _u.mutation.EscalatedAtCleared() {
		_spec.ClearField(incident.FieldEscalatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EscalationLevel(); ok {
		_spec.SetField(incident.FieldEscalationLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEscalationLevel(); ok {
		_spec.AddField(incident.FieldEscalationLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsAutomated(); ok {
		_spec.SetField(incident.FieldIsAutomated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMajorIncident(); ok {
		_spec.SetField(incident.FieldIsMajorIncident, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(incident.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(incident.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.WorkItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   incident.WorkItemTable,
			Columns: []string{incident.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   incident.WorkItemTable,
			Columns: []string{incident.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelatedIncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelatedIncidentsIDs(); len(nodes) > 0 && !_u.mutation.RelatedIncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelatedIncidentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentEventsIDs(); len(nodes) > 0 && !_u.mutation.IncidentEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentAlertsIDs(); len(nodes) > 0 && !_u.mutation.IncidentAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentMetricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentMetricsIDs(); len(nodes) > 0 && !_u.mutation.IncidentMetricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentMetricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentIncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentIncidentIDs(); len(nodes) > 0 && !_u.mutation.ParentIncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigurationItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigurationItemsIDs(); len(nodes) > 0 && !_u.mutation.ConfigurationItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigurationItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !_u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IncidentUpdateOne is the builder for updating a single Incident entity.
type IncidentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IncidentMutation
}

// SetType sets the "type" field.
func (_u *IncidentUpdateOne) SetType(v string) *IncidentUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableType(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSeverity sets the "severity" field.
func (_u *IncidentUpdateOne) SetSeverity(v string) *IncidentUpdateOne {
	_u.mutation.SetSeverity(v)
	return _u
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableSeverity(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetSeverity(*v)
	}
	return _u
}

// SetImpact sets the "impact" field.
func (_u *IncidentUpdateOne) SetImpact(v string) *IncidentUpdateOne {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableImpact(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// SetUrgency sets the "urgency" field.
func (_u *IncidentUpdateOne) SetUrgency(v string) *IncidentUpdateOne {
	_u.mutation.SetUrgency(v)
	return _u
}

// SetNillableUrgency sets the "urgency" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableUrgency(v *string) *IncidentUpdateOne {
	if v != nil {
		_u.SetUrgency(*v)
	}
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *IncidentUpdateOne) SetWorkItemID(v int) *IncidentUpdateOne {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableWorkItemID(v *int) *IncidentUpdateOne {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetConfigurationItemID sets the "configuration_item_id" field.
func (_u *IncidentUpdateOne) SetConfigurationItemID(v int) *IncidentUpdateOne {
	_u.mutation.ResetConfigurationItemID()
	_u.mutation.SetConfigurationItemID(v)
	return _u
}

// SetNillableConfigurationItemID sets the "configuration_item_id" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableConfigurationItemID(v *int) *IncidentUpdateOne {
	if v != nil {
		_u.SetConfigurationItemID(*v)
	}
	return _u
}

// AddConfigurationItemID adds value to the "configuration_item_id" field.
func (_u *IncidentUpdateOne) AddConfigurationItemID(v int) *IncidentUpdateOne {
	_u.mutation.AddConfigurationItemID(v)
	return _u
}

// ClearConfigurationItemID clears the value of the "configuration_item_id" field.
func (_u *IncidentUpdateOne) ClearConfigurationItemID() *IncidentUpdateOne {
	_u.mutation.ClearConfigurationItemID()
	return _u
}

// SetImpactAnalysis sets the "impact_analysis" field.
func (_u *IncidentUpdateOne) SetImpactAnalysis(v map[string]interface{}) *IncidentUpdateOne {
	_u.mutation.SetImpactAnalysis(v)
	return _u
}

// ClearImpactAnalysis clears the value of the "impact_analysis" field.
func (_u *IncidentUpdateOne) ClearImpactAnalysis() *IncidentUpdateOne {
	_u.mutation.ClearImpactAnalysis()
	return _u
}

// SetRootCause sets the "root_cause" field.
func (_u *IncidentUpdateOne) SetRootCause(v map[string]interface{}) *IncidentUpdateOne {
	_u.mutation.SetRootCause(v)
	return _u
}

// ClearRootCause clears the value of the "root_cause" field.
func (_u *IncidentUpdateOne) ClearRootCause() *IncidentUpdateOne {
	_u.mutation.ClearRootCause()
	return _u
}

// SetResolutionSteps sets the "resolution_steps" field.
func (_u *IncidentUpdateOne) SetResolutionSteps(v []map[string]interface{}) *IncidentUpdateOne {
	_u.mutation.SetResolutionSteps(v)
	return _u
}

// AppendResolutionSteps appends value to the "resolution_steps" field.
func (_u *IncidentUpdateOne) AppendResolutionSteps(v []map[string]interface{}) *IncidentUpdateOne {
	_u.mutation.AppendResolutionSteps(v)
	return _u
}

// ClearResolutionSteps clears the value of the "resolution_steps" field.
func (_u *IncidentUpdateOne) ClearResolutionSteps() *IncidentUpdateOne {
	_u.mutation.ClearResolutionSteps()
	return _u
}

// SetDetectedAt sets the "detected_at" field.
func (_u *IncidentUpdateOne) SetDetectedAt(v time.Time) *IncidentUpdateOne {
	_u.mutation.SetDetectedAt(v)
	return _u
}

// SetNillableDetectedAt sets the "detected_at" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableDetectedAt(v *time.Time) *IncidentUpdateOne {
	if v != nil {
		_u.SetDetectedAt(*v)
	}
	return _u
}

// SetEscalatedAt sets the "escalated_at" field.
func (_u *IncidentUpdateOne) SetEscalatedAt(v time.Time) *IncidentUpdateOne {
	_u.mutation.SetEscalatedAt(v)
	return _u
}

// SetNillableEscalatedAt sets the "escalated_at" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableEscalatedAt(v *time.Time) *IncidentUpdateOne {
	if v != nil {
		_u.SetEscalatedAt(*v)
	}
	return _u
}

// ClearEscalatedAt clears the value of the "escalated_at" field.
func (_u *IncidentUpdateOne) ClearEscalatedAt() *IncidentUpdateOne {
	_u.mutation.ClearEscalatedAt()
	return _u
}

// SetEscalationLevel sets the "escalation_level" field.
func (_u *IncidentUpdateOne) SetEscalationLevel(v int) *IncidentUpdateOne {
	_u.mutation.ResetEscalationLevel()
	_u.mutation.SetEscalationLevel(v)
	return _u
}

// SetNillableEscalationLevel sets the "escalation_level" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableEscalationLevel(v *int) *IncidentUpdateOne {
	if v != nil {
		_u.SetEscalationLevel(*v)
	}
	return _u
}

// AddEscalationLevel adds value to the "escalation_level" field.
func (_u *IncidentUpdateOne) AddEscalationLevel(v int) *IncidentUpdateOne {
	_u.mutation.AddEscalationLevel(v)
	return _u
}

// SetIsAutomated sets the "is_automated" field.
func (_u *IncidentUpdateOne) SetIsAutomated(v bool) *IncidentUpdateOne {
	_u.mutation.SetIsAutomated(v)
	return _u
}

// SetNillableIsAutomated sets the "is_automated" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableIsAutomated(v *bool) *IncidentUpdateOne {
	if v != nil {
		_u.SetIsAutomated(*v)
	}
	return _u
}

// SetIsMajorIncident sets the "is_major_incident" field.
func (_u *IncidentUpdateOne) SetIsMajorIncident(v bool) *IncidentUpdateOne {
	_u.mutation.SetIsMajorIncident(v)
	return _u
}

// SetNillableIsMajorIncident sets the "is_major_incident" field if the given value is not nil.
func (_u *IncidentUpdateOne) SetNillableIsMajorIncident(v *bool) *IncidentUpdateOne {
	if v != nil {
		_u.SetIsMajorIncident(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *IncidentUpdateOne) SetMetadata(v map[string]interface{}) *IncidentUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *IncidentUpdateOne) ClearMetadata() *IncidentUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetWorkItem sets the "work_item" edge to the Ticket entity.
func (_u *IncidentUpdateOne) SetWorkItem(v *Ticket) *IncidentUpdateOne {
	return _u.SetWorkItemID(v.ID)
}

// AddRelatedIncidentIDs adds the "related_incidents" edge to the Incident entity by IDs.
func (_u *IncidentUpdateOne) AddRelatedIncidentIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddRelatedIncidentIDs(ids...)
	return _u
}

// AddRelatedIncidents adds the "related_incidents" edges to the Incident entity.
func (_u *IncidentUpdateOne) AddRelatedIncidents(v ...*Incident) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRelatedIncidentIDs(ids...)
}

// AddIncidentEventIDs adds the "incident_events" edge to the IncidentEvent entity by IDs.
func (_u *IncidentUpdateOne) AddIncidentEventIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddIncidentEventIDs(ids...)
	return _u
}

// AddIncidentEvents adds the "incident_events" edges to the IncidentEvent entity.
func (_u *IncidentUpdateOne) AddIncidentEvents(v ...*IncidentEvent) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentEventIDs(ids...)
}

// AddIncidentAlertIDs adds the "incident_alerts" edge to the IncidentAlert entity by IDs.
func (_u *IncidentUpdateOne) AddIncidentAlertIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddIncidentAlertIDs(ids...)
	return _u
}

// AddIncidentAlerts adds the "incident_alerts" edges to the IncidentAlert entity.
func (_u *IncidentUpdateOne) AddIncidentAlerts(v ...*IncidentAlert) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentAlertIDs(ids...)
}

// AddIncidentMetricIDs adds the "incident_metrics" edge to the IncidentMetric entity by IDs.
func (_u *IncidentUpdateOne) AddIncidentMetricIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddIncidentMetricIDs(ids...)
	return _u
}

// AddIncidentMetrics adds the "incident_metrics" edges to the IncidentMetric entity.
func (_u *IncidentUpdateOne) AddIncidentMetrics(v ...*IncidentMetric) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentMetricIDs(ids...)
}

// AddParentIncidentIDs adds the "parent_incident" edge to the Incident entity by IDs.
func (_u *IncidentUpdateOne) AddParentIncidentIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddParentIncidentIDs(ids...)
	return _u
}

// AddParentIncident adds the "parent_incident" edges to the Incident entity.
func (_u *IncidentUpdateOne) AddParentIncident(v ...*Incident) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddParentIncidentIDs(ids...)
}

// AddConfigurationItemIDs adds the "configuration_items" edge to the ConfigurationItem entity by IDs.
func (_u *IncidentUpdateOne) AddConfigurationItemIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddConfigurationItemIDs(ids...)
	return _u
}

// AddConfigurationItems adds the "configuration_items" edges to the ConfigurationItem entity.
func (_u *IncidentUpdateOne) AddConfigurationItems(v ...*ConfigurationItem) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConfigurationItemIDs(ids...)
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (_u *IncidentUpdateOne) AddProblemIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.AddProblemIDs(ids...)
	return _u
}

// AddProblems adds the "problems" edges to the Problem entity.
func (_u *IncidentUpdateOne) AddProblems(v ...*Problem) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddProblemIDs(ids...)
}

// Mutation returns the IncidentMutation object of the builder.
func (_u *IncidentUpdateOne) Mutation() *IncidentMutation {
	return _u.mutation
}

// ClearWorkItem clears the "work_item" edge to the Ticket entity.
func (_u *IncidentUpdateOne) ClearWorkItem() *IncidentUpdateOne {
	_u.mutation.ClearWorkItem()
	return _u
}

// ClearRelatedIncidents clears all "related_incidents" edges to the Incident entity.
func (_u *IncidentUpdateOne) ClearRelatedIncidents() *IncidentUpdateOne {
	_u.mutation.ClearRelatedIncidents()
	return _u
}

// RemoveRelatedIncidentIDs removes the "related_incidents" edge to Incident entities by IDs.
func (_u *IncidentUpdateOne) RemoveRelatedIncidentIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveRelatedIncidentIDs(ids...)
	return _u
}

// RemoveRelatedIncidents removes "related_incidents" edges to Incident entities.
func (_u *IncidentUpdateOne) RemoveRelatedIncidents(v ...*Incident) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRelatedIncidentIDs(ids...)
}

// ClearIncidentEvents clears all "incident_events" edges to the IncidentEvent entity.
func (_u *IncidentUpdateOne) ClearIncidentEvents() *IncidentUpdateOne {
	_u.mutation.ClearIncidentEvents()
	return _u
}

// RemoveIncidentEventIDs removes the "incident_events" edge to IncidentEvent entities by IDs.
func (_u *IncidentUpdateOne) RemoveIncidentEventIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveIncidentEventIDs(ids...)
	return _u
}

// RemoveIncidentEvents removes "incident_events" edges to IncidentEvent entities.
func (_u *IncidentUpdateOne) RemoveIncidentEvents(v ...*IncidentEvent) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentEventIDs(ids...)
}

// ClearIncidentAlerts clears all "incident_alerts" edges to the IncidentAlert entity.
func (_u *IncidentUpdateOne) ClearIncidentAlerts() *IncidentUpdateOne {
	_u.mutation.ClearIncidentAlerts()
	return _u
}

// RemoveIncidentAlertIDs removes the "incident_alerts" edge to IncidentAlert entities by IDs.
func (_u *IncidentUpdateOne) RemoveIncidentAlertIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveIncidentAlertIDs(ids...)
	return _u
}

// RemoveIncidentAlerts removes "incident_alerts" edges to IncidentAlert entities.
func (_u *IncidentUpdateOne) RemoveIncidentAlerts(v ...*IncidentAlert) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentAlertIDs(ids...)
}

// ClearIncidentMetrics clears all "incident_metrics" edges to the IncidentMetric entity.
func (_u *IncidentUpdateOne) ClearIncidentMetrics() *IncidentUpdateOne {
	_u.mutation.ClearIncidentMetrics()
	return _u
}

// RemoveIncidentMetricIDs removes the "incident_metrics" edge to IncidentMetric entities by IDs.
func (_u *IncidentUpdateOne) RemoveIncidentMetricIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveIncidentMetricIDs(ids...)
	return _u
}

// RemoveIncidentMetrics removes "incident_metrics" edges to IncidentMetric entities.
func (_u *IncidentUpdateOne) RemoveIncidentMetrics(v ...*IncidentMetric) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentMetricIDs(ids...)
}

// ClearParentIncident clears all "parent_incident" edges to the Incident entity.
func (_u *IncidentUpdateOne) ClearParentIncident() *IncidentUpdateOne {
	_u.mutation.ClearParentIncident()
	return _u
}

// RemoveParentIncidentIDs removes the "parent_incident" edge to Incident entities by IDs.
func (_u *IncidentUpdateOne) RemoveParentIncidentIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveParentIncidentIDs(ids...)
	return _u
}

// RemoveParentIncident removes "parent_incident" edges to Incident entities.
func (_u *IncidentUpdateOne) RemoveParentIncident(v ...*Incident) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveParentIncidentIDs(ids...)
}

// ClearConfigurationItems clears all "configuration_items" edges to the ConfigurationItem entity.
func (_u *IncidentUpdateOne) ClearConfigurationItems() *IncidentUpdateOne {
	_u.mutation.ClearConfigurationItems()
	return _u
}

// RemoveConfigurationItemIDs removes the "configuration_items" edge to ConfigurationItem entities by IDs.
func (_u *IncidentUpdateOne) RemoveConfigurationItemIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveConfigurationItemIDs(ids...)
	return _u
}

// RemoveConfigurationItems removes "configuration_items" edges to ConfigurationItem entities.
func (_u *IncidentUpdateOne) RemoveConfigurationItems(v ...*ConfigurationItem) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConfigurationItemIDs(ids...)
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (_u *IncidentUpdateOne) ClearProblems() *IncidentUpdateOne {
	_u.mutation.ClearProblems()
	return _u
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (_u *IncidentUpdateOne) RemoveProblemIDs(ids ...int) *IncidentUpdateOne {
	_u.mutation.RemoveProblemIDs(ids...)
	return _u
}

// RemoveProblems removes "problems" edges to Problem entities.
func (_u *IncidentUpdateOne) RemoveProblems(v ...*Problem) *IncidentUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveProblemIDs(ids...)
}

// Where appends a list predicates to the IncidentUpdate builder.
func (_u *IncidentUpdateOne) Where(ps ...predicate.Incident) *IncidentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IncidentUpdateOne) Select(field string, fields ...string) *IncidentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Incident entity.
func (_u *IncidentUpdateOne) Save(ctx context.Context) (*Incident, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IncidentUpdateOne) SaveX(ctx context.Context) *Incident {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IncidentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IncidentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IncidentUpdateOne) check() error {
	if v, ok := _u.mutation.Impact(); ok {
		if err := incident.ImpactValidator(v); err != nil {
			return &ValidationError{Name: "impact", err: fmt.Errorf(`ent: validator failed for field "Incident.impact": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Urgency(); ok {
		if err := incident.UrgencyValidator(v); err != nil {
			return &ValidationError{Name: "urgency", err: fmt.Errorf(`ent: validator failed for field "Incident.urgency": %w`, err)}
		}
	}
	if _u.mutation.WorkItemCleared() && len(_u.mutation.WorkItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Incident.work_item"`)
	}
	return nil
}

func (_u *IncidentUpdateOne) sqlSave(ctx context.Context) (_node *Incident, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(incident.Table, incident.Columns, sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Incident.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, incident.FieldID)
		for _, f := range fields {
			if !incident.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != incident.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(incident.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Severity(); ok {
		_spec.SetField(incident.FieldSeverity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(incident.FieldImpact, field.TypeString, value)
	}
	if value, ok := _u.mutation.Urgency(); ok {
		_spec.SetField(incident.FieldUrgency, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConfigurationItemID(); ok {
		_spec.SetField(incident.FieldConfigurationItemID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigurationItemID(); ok {
		_spec.AddField(incident.FieldConfigurationItemID, field.TypeInt, value)
	}
	if _u.mutation.ConfigurationItemIDCleared() {
		_spec.ClearField(incident.FieldConfigurationItemID, field.TypeInt)
	}
	if value, ok := _u.mutation.ImpactAnalysis(); ok {
		_spec.SetField(incident.FieldImpactAnalysis, field.TypeJSON, value)
	}
	if _u.mutation.ImpactAnalysisCleared() {
		_spec.ClearField(incident.FieldImpactAnalysis, field.TypeJSON)
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(incident.FieldRootCause, field.TypeJSON, value)
	}
	if _u.mutation.RootCauseCleared() {
		_spec.ClearField(incident.FieldRootCause, field.TypeJSON)
	}
	if value, ok := _u.mutation.ResolutionSteps(); ok {
		_spec.SetField(incident.FieldResolutionSteps, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResolutionSteps(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, incident.FieldResolutionSteps, value)
		})
	}
	if _u.mutation.ResolutionStepsCleared() {
		_spec.ClearField(incident.FieldResolutionSteps, field.TypeJSON)
	}
	if value, ok := _u.mutation.DetectedAt(); ok {
		_spec.SetField(incident.FieldDetectedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EscalatedAt(); ok {
		_spec.SetField(incident.FieldEscalatedAt, field.TypeTime, value)
	}
	if _u.mutation.EscalatedAtCleared() {
		_spec.ClearField(incident.FieldEscalatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.EscalationLevel(); ok {
		_spec.SetField(incident.FieldEscalationLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEscalationLevel(); ok {
		_spec.AddField(incident.FieldEscalationLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsAutomated(); ok {
		_spec.SetField(incident.FieldIsAutomated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsMajorIncident(); ok {
		_spec.SetField(incident.FieldIsMajorIncident, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(incident.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(incident.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.WorkItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   incident.WorkItemTable,
			Columns: []string{incident.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   incident.WorkItemTable,
			Columns: []string{incident.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RelatedIncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRelatedIncidentsIDs(); len(nodes) > 0 && !_u.mutation.RelatedIncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RelatedIncidentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   incident.RelatedIncidentsTable,
			Columns: incident.RelatedIncidentsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentEventsIDs(); len(nodes) > 0 && !_u.mutation.IncidentEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentEventsTable,
			Columns: []string{incident.IncidentEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentAlertsIDs(); len(nodes) > 0 && !_u.mutation.IncidentAlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentAlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentAlertsTable,
			Columns: []string{incident.IncidentAlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentalert.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentMetricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentMetricsIDs(); len(nodes) > 0 && !_u.mutation.IncidentMetricsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentMetricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   incident.IncidentMetricsTable,
			Columns: []string{incident.IncidentMetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentmetric.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentIncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedParentIncidentIDs(); len(nodes) > 0 && !_u.mutation.ParentIncidentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIncidentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ParentIncidentTable,
			Columns: incident.ParentIncidentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConfigurationItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConfigurationItemsIDs(); len(nodes) > 0 && !_u.mutation.ConfigurationItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConfigurationItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ConfigurationItemsTable,
			Columns: incident.ConfigurationItemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(configurationitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !_u.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   incident.ProblemsTable,
			Columns: incident.ProblemsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Incident{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{incident.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
