// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/incidentruleactionreceipt"
	"itsm-backend/ent/incidentruleexecution"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IncidentRuleActionReceiptCreate is the builder for creating a IncidentRuleActionReceipt entity.
type IncidentRuleActionReceiptCreate struct {
	config
	mutation *IncidentRuleActionReceiptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *IncidentRuleActionReceiptCreate) SetTenantID(v int) *IncidentRuleActionReceiptCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetExecutionID sets the "execution_id" field.
func (_c *IncidentRuleActionReceiptCreate) SetExecutionID(v int) *IncidentRuleActionReceiptCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetActionIndex sets the "action_index" field.
func (_c *IncidentRuleActionReceiptCreate) SetActionIndex(v int) *IncidentRuleActionReceiptCreate {
	_c.mutation.SetActionIndex(v)
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *IncidentRuleActionReceiptCreate) SetCompletedAt(v time.Time) *IncidentRuleActionReceiptCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *IncidentRuleActionReceiptCreate) SetNillableCompletedAt(v *time.Time) *IncidentRuleActionReceiptCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetExecution sets the "execution" edge to the IncidentRuleExecution entity.
func (_c *IncidentRuleActionReceiptCreate) SetExecution(v *IncidentRuleExecution) *IncidentRuleActionReceiptCreate {
	return _c.SetExecutionID(v.ID)
}

// Mutation returns the IncidentRuleActionReceiptMutation object of the builder.
func (_c *IncidentRuleActionReceiptCreate) Mutation() *IncidentRuleActionReceiptMutation {
	return _c.mutation
}

// Save creates the IncidentRuleActionReceipt in the database.
func (_c *IncidentRuleActionReceiptCreate) Save(ctx context.Context) (*IncidentRuleActionReceipt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IncidentRuleActionReceiptCreate) SaveX(ctx context.Context) *IncidentRuleActionReceipt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentRuleActionReceiptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentRuleActionReceiptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IncidentRuleActionReceiptCreate) defaults() {
	if _, ok := _c.mutation.CompletedAt(); !ok {
		v := incidentruleactionreceipt.DefaultCompletedAt()
		_c.mutation.SetCompletedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IncidentRuleActionReceiptCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "IncidentRuleActionReceipt.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := incidentruleactionreceipt.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "IncidentRuleActionReceipt.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "IncidentRuleActionReceipt.execution_id"`)}
	}
	if v, ok := _c.mutation.ExecutionID(); ok {
		if err := incidentruleactionreceipt.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "IncidentRuleActionReceipt.execution_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActionIndex(); !ok {
		return &ValidationError{Name: "action_index", err: errors.New(`ent: missing required field "IncidentRuleActionReceipt.action_index"`)}
	}
	if v, ok := _c.mutation.ActionIndex(); ok {
		if err := incidentruleactionreceipt.ActionIndexValidator(v); err != nil {
			return &ValidationError{Name: "action_index", err: fmt.Errorf(`ent: validator failed for field "IncidentRuleActionReceipt.action_index": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CompletedAt(); !ok {
		return &ValidationError{Name: "completed_at", err: errors.New(`ent: missing required field "IncidentRuleActionReceipt.completed_at"`)}
	}
	if len(_c.mutation.ExecutionIDs()) == 0 {
		return &ValidationError{Name: "execution", err: errors.New(`ent: missing required edge "IncidentRuleActionReceipt.execution"`)}
	}
	return nil
}

func (_c *IncidentRuleActionReceiptCreate) sqlSave(ctx context.Context) (*IncidentRuleActionReceipt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IncidentRuleActionReceiptCreate) createSpec() (*IncidentRuleActionReceipt, *sqlgraph.CreateSpec) {
	var (
		_node = &IncidentRuleActionReceipt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(incidentruleactionreceipt.Table, sqlgraph.NewFieldSpec(incidentruleactionreceipt.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(incidentruleactionreceipt.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ActionIndex(); ok {
		_spec.SetField(incidentruleactionreceipt.FieldActionIndex, field.TypeInt, value)
		_node.ActionIndex = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(incidentruleactionreceipt.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if nodes := _c.mutation.ExecutionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   incidentruleactionreceipt.ExecutionTable,
			Columns: []string{incidentruleactionreceipt.ExecutionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incidentruleexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ExecutionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IncidentRuleActionReceipt.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentRuleActionReceiptUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentRuleActionReceiptCreate) OnConflict(opts ...sql.ConflictOption) *IncidentRuleActionReceiptUpsertOne {
	_c.conflict = opts
	return &IncidentRuleActionReceiptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentRuleActionReceiptCreate) OnConflictColumns(columns ...string) *IncidentRuleActionReceiptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentRuleActionReceiptUpsertOne{
		create: _c,
	}
}

type (
	// IncidentRuleActionReceiptUpsertOne is the builder for "upsert"-ing
	//  one IncidentRuleActionReceipt node.
	IncidentRuleActionReceiptUpsertOne struct {
		create *IncidentRuleActionReceiptCreate
	}

	// IncidentRuleActionReceiptUpsert is the "OnConflict" setter.
	IncidentRuleActionReceiptUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IncidentRuleActionReceiptUpsertOne) UpdateNewValues() *IncidentRuleActionReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(incidentruleactionreceipt.FieldTenantID)
		}
		if _, exists := u.create.mutation.ExecutionID(); exists {
			s.SetIgnore(incidentruleactionreceipt.FieldExecutionID)
		}
		if _, exists := u.create.mutation.ActionIndex(); exists {
			s.SetIgnore(incidentruleactionreceipt.FieldActionIndex)
		}
		if _, exists := u.create.mutation.CompletedAt(); exists {
			s.SetIgnore(incidentruleactionreceipt.FieldCompletedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IncidentRuleActionReceiptUpsertOne) Ignore() *IncidentRuleActionReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentRuleActionReceiptUpsertOne) DoNothing() *IncidentRuleActionReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentRuleActionReceiptCreate.OnConflict
// documentation for more info.
func (u *IncidentRuleActionReceiptUpsertOne) Update(set func(*IncidentRuleActionReceiptUpsert)) *IncidentRuleActionReceiptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentRuleActionReceiptUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *IncidentRuleActionReceiptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentRuleActionReceiptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentRuleActionReceiptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IncidentRuleActionReceiptUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IncidentRuleActionReceiptUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IncidentRuleActionReceiptCreateBulk is the builder for creating many IncidentRuleActionReceipt entities in bulk.
type IncidentRuleActionReceiptCreateBulk struct {
	config
	err      error
	builders []*IncidentRuleActionReceiptCreate
	conflict []sql.ConflictOption
}

// Save creates the IncidentRuleActionReceipt entities in the database.
func (_c *IncidentRuleActionReceiptCreateBulk) Save(ctx context.Context) ([]*IncidentRuleActionReceipt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IncidentRuleActionReceipt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IncidentRuleActionReceiptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IncidentRuleActionReceiptCreateBulk) SaveX(ctx context.Context) []*IncidentRuleActionReceipt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IncidentRuleActionReceiptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IncidentRuleActionReceiptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IncidentRuleActionReceipt.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IncidentRuleActionReceiptUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *IncidentRuleActionReceiptCreateBulk) OnConflict(opts ...sql.ConflictOption) *IncidentRuleActionReceiptUpsertBulk {
	_c.conflict = opts
	return &IncidentRuleActionReceiptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IncidentRuleActionReceiptCreateBulk) OnConflictColumns(columns ...string) *IncidentRuleActionReceiptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IncidentRuleActionReceiptUpsertBulk{
		create: _c,
	}
}

// IncidentRuleActionReceiptUpsertBulk is the builder for "upsert"-ing
// a bulk of IncidentRuleActionReceipt nodes.
type IncidentRuleActionReceiptUpsertBulk struct {
	create *IncidentRuleActionReceiptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *IncidentRuleActionReceiptUpsertBulk) UpdateNewValues() *IncidentRuleActionReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(incidentruleactionreceipt.FieldTenantID)
			}
			if _, exists := b.mutation.ExecutionID(); exists {
				s.SetIgnore(incidentruleactionreceipt.FieldExecutionID)
			}
			if _, exists := b.mutation.ActionIndex(); exists {
				s.SetIgnore(incidentruleactionreceipt.FieldActionIndex)
			}
			if _, exists := b.mutation.CompletedAt(); exists {
				s.SetIgnore(incidentruleactionreceipt.FieldCompletedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IncidentRuleActionReceipt.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IncidentRuleActionReceiptUpsertBulk) Ignore() *IncidentRuleActionReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IncidentRuleActionReceiptUpsertBulk) DoNothing() *IncidentRuleActionReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IncidentRuleActionReceiptCreateBulk.OnConflict
// documentation for more info.
func (u *IncidentRuleActionReceiptUpsertBulk) Update(set func(*IncidentRuleActionReceiptUpsert)) *IncidentRuleActionReceiptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IncidentRuleActionReceiptUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *IncidentRuleActionReceiptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IncidentRuleActionReceiptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IncidentRuleActionReceiptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IncidentRuleActionReceiptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
