// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/itemversion"
	"itsm-backend/ent/marketplaceitem"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemVersionCreate is the builder for creating a ItemVersion entity.
type ItemVersionCreate struct {
	config
	mutation *ItemVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetItemID sets the "item_id" field.
func (_c *ItemVersionCreate) SetItemID(v int) *ItemVersionCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ItemVersionCreate) SetVersion(v string) *ItemVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetChangelog sets the "changelog" field.
func (_c *ItemVersionCreate) SetChangelog(v string) *ItemVersionCreate {
	_c.mutation.SetChangelog(v)
	return _c
}

// SetNillableChangelog sets the "changelog" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableChangelog(v *string) *ItemVersionCreate {
	if v != nil {
		_c.SetChangelog(*v)
	}
	return _c
}

// SetDownloadURL sets the "download_url" field.
func (_c *ItemVersionCreate) SetDownloadURL(v string) *ItemVersionCreate {
	_c.mutation.SetDownloadURL(v)
	return _c
}

// SetNillableDownloadURL sets the "download_url" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableDownloadURL(v *string) *ItemVersionCreate {
	if v != nil {
		_c.SetDownloadURL(*v)
	}
	return _c
}

// SetManifestPath sets the "manifest_path" field.
func (_c *ItemVersionCreate) SetManifestPath(v string) *ItemVersionCreate {
	_c.mutation.SetManifestPath(v)
	return _c
}

// SetNillableManifestPath sets the "manifest_path" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableManifestPath(v *string) *ItemVersionCreate {
	if v != nil {
		_c.SetManifestPath(*v)
	}
	return _c
}

// SetMinSystemVersion sets the "min_system_version" field.
func (_c *ItemVersionCreate) SetMinSystemVersion(v string) *ItemVersionCreate {
	_c.mutation.SetMinSystemVersion(v)
	return _c
}

// SetNillableMinSystemVersion sets the "min_system_version" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableMinSystemVersion(v *string) *ItemVersionCreate {
	if v != nil {
		_c.SetMinSystemVersion(*v)
	}
	return _c
}

// SetDependencies sets the "dependencies" field.
func (_c *ItemVersionCreate) SetDependencies(v map[string]string) *ItemVersionCreate {
	_c.mutation.SetDependencies(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ItemVersionCreate) SetStatus(v itemversion.Status) *ItemVersionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableStatus(v *itemversion.Status) *ItemVersionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetDownloadCount sets the "download_count" field.
func (_c *ItemVersionCreate) SetDownloadCount(v int) *ItemVersionCreate {
	_c.mutation.SetDownloadCount(v)
	return _c
}

// SetNillableDownloadCount sets the "download_count" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableDownloadCount(v *int) *ItemVersionCreate {
	if v != nil {
		_c.SetDownloadCount(*v)
	}
	return _c
}

// SetReleasedAt sets the "released_at" field.
func (_c *ItemVersionCreate) SetReleasedAt(v time.Time) *ItemVersionCreate {
	_c.mutation.SetReleasedAt(v)
	return _c
}

// SetNillableReleasedAt sets the "released_at" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableReleasedAt(v *time.Time) *ItemVersionCreate {
	if v != nil {
		_c.SetReleasedAt(*v)
	}
	return _c
}

// SetConfigSchema sets the "config_schema" field.
func (_c *ItemVersionCreate) SetConfigSchema(v map[string]interface{}) *ItemVersionCreate {
	_c.mutation.SetConfigSchema(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemVersionCreate) SetCreatedAt(v time.Time) *ItemVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableCreatedAt(v *time.Time) *ItemVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemVersionCreate) SetUpdatedAt(v time.Time) *ItemVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemVersionCreate) SetNillableUpdatedAt(v *time.Time) *ItemVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetItem sets the "item" edge to the MarketplaceItem entity.
func (_c *ItemVersionCreate) SetItem(v *MarketplaceItem) *ItemVersionCreate {
	return _c.SetItemID(v.ID)
}

// Mutation returns the ItemVersionMutation object of the builder.
func (_c *ItemVersionCreate) Mutation() *ItemVersionMutation {
	return _c.mutation
}

// Save creates the ItemVersion in the database.
func (_c *ItemVersionCreate) Save(ctx context.Context) (*ItemVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemVersionCreate) SaveX(ctx context.Context) *ItemVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemVersionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := itemversion.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		v := itemversion.DefaultDownloadCount
		_c.mutation.SetDownloadCount(v)
	}
	if _, ok := _c.mutation.ReleasedAt(); !ok {
		v := itemversion.DefaultReleasedAt()
		_c.mutation.SetReleasedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itemversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itemversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemVersionCreate) check() error {
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "ItemVersion.item_id"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "ItemVersion.version"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ItemVersion.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := itemversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ItemVersion.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DownloadCount(); !ok {
		return &ValidationError{Name: "download_count", err: errors.New(`ent: missing required field "ItemVersion.download_count"`)}
	}
	if _, ok := _c.mutation.ReleasedAt(); !ok {
		return &ValidationError{Name: "released_at", err: errors.New(`ent: missing required field "ItemVersion.released_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemVersion.updated_at"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "ItemVersion.item"`)}
	}
	return nil
}

func (_c *ItemVersionCreate) sqlSave(ctx context.Context) (*ItemVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemVersionCreate) createSpec() (*ItemVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itemversion.Table, sqlgraph.NewFieldSpec(itemversion.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(itemversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Changelog(); ok {
		_spec.SetField(itemversion.FieldChangelog, field.TypeString, value)
		_node.Changelog = value
	}
	if value, ok := _c.mutation.DownloadURL(); ok {
		_spec.SetField(itemversion.FieldDownloadURL, field.TypeString, value)
		_node.DownloadURL = value
	}
	if value, ok := _c.mutation.ManifestPath(); ok {
		_spec.SetField(itemversion.FieldManifestPath, field.TypeString, value)
		_node.ManifestPath = value
	}
	if value, ok := _c.mutation.MinSystemVersion(); ok {
		_spec.SetField(itemversion.FieldMinSystemVersion, field.TypeString, value)
		_node.MinSystemVersion = value
	}
	if value, ok := _c.mutation.Dependencies(); ok {
		_spec.SetField(itemversion.FieldDependencies, field.TypeJSON, value)
		_node.Dependencies = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(itemversion.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.DownloadCount(); ok {
		_spec.SetField(itemversion.FieldDownloadCount, field.TypeInt, value)
		_node.DownloadCount = value
	}
	if value, ok := _c.mutation.ReleasedAt(); ok {
		_spec.SetField(itemversion.FieldReleasedAt, field.TypeTime, value)
		_node.ReleasedAt = value
	}
	if value, ok := _c.mutation.ConfigSchema(); ok {
		_spec.SetField(itemversion.FieldConfigSchema, field.TypeJSON, value)
		_node.ConfigSchema = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itemversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itemversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemversion.ItemTable,
			Columns: []string{itemversion.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(marketplaceitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemVersion.Create().
//		SetItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemVersionUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemVersionCreate) OnConflict(opts ...sql.ConflictOption) *ItemVersionUpsertOne {
	_c.conflict = opts
	return &ItemVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemVersionCreate) OnConflictColumns(columns ...string) *ItemVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemVersionUpsertOne{
		create: _c,
	}
}

type (
	// ItemVersionUpsertOne is the builder for "upsert"-ing
	//  one ItemVersion node.
	ItemVersionUpsertOne struct {
		create *ItemVersionCreate
	}

	// ItemVersionUpsert is the "OnConflict" setter.
	ItemVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetItemID sets the "item_id" field.
func (u *ItemVersionUpsert) SetItemID(v int) *ItemVersionUpsert {
	u.Set(itemversion.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateItemID() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldItemID)
	return u
}

// SetVersion sets the "version" field.
func (u *ItemVersionUpsert) SetVersion(v string) *ItemVersionUpsert {
	u.Set(itemversion.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateVersion() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldVersion)
	return u
}

// SetChangelog sets the "changelog" field.
func (u *ItemVersionUpsert) SetChangelog(v string) *ItemVersionUpsert {
	u.Set(itemversion.FieldChangelog, v)
	return u
}

// UpdateChangelog sets the "changelog" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateChangelog() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldChangelog)
	return u
}

// ClearChangelog clears the value of the "changelog" field.
func (u *ItemVersionUpsert) ClearChangelog() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldChangelog)
	return u
}

// SetDownloadURL sets the "download_url" field.
func (u *ItemVersionUpsert) SetDownloadURL(v string) *ItemVersionUpsert {
	u.Set(itemversion.FieldDownloadURL, v)
	return u
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateDownloadURL() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldDownloadURL)
	return u
}

// ClearDownloadURL clears the value of the "download_url" field.
func (u *ItemVersionUpsert) ClearDownloadURL() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldDownloadURL)
	return u
}

// SetManifestPath sets the "manifest_path" field.
func (u *ItemVersionUpsert) SetManifestPath(v string) *ItemVersionUpsert {
	u.Set(itemversion.FieldManifestPath, v)
	return u
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateManifestPath() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldManifestPath)
	return u
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *ItemVersionUpsert) ClearManifestPath() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldManifestPath)
	return u
}

// SetMinSystemVersion sets the "min_system_version" field.
func (u *ItemVersionUpsert) SetMinSystemVersion(v string) *ItemVersionUpsert {
	u.Set(itemversion.FieldMinSystemVersion, v)
	return u
}

// UpdateMinSystemVersion sets the "min_system_version" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateMinSystemVersion() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldMinSystemVersion)
	return u
}

// ClearMinSystemVersion clears the value of the "min_system_version" field.
func (u *ItemVersionUpsert) ClearMinSystemVersion() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldMinSystemVersion)
	return u
}

// SetDependencies sets the "dependencies" field.
func (u *ItemVersionUpsert) SetDependencies(v map[string]string) *ItemVersionUpsert {
	u.Set(itemversion.FieldDependencies, v)
	return u
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateDependencies() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldDependencies)
	return u
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ItemVersionUpsert) ClearDependencies() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldDependencies)
	return u
}

// SetStatus sets the "status" field.
func (u *ItemVersionUpsert) SetStatus(v itemversion.Status) *ItemVersionUpsert {
	u.Set(itemversion.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateStatus() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldStatus)
	return u
}

// SetDownloadCount sets the "download_count" field.
func (u *ItemVersionUpsert) SetDownloadCount(v int) *ItemVersionUpsert {
	u.Set(itemversion.FieldDownloadCount, v)
	return u
}

// UpdateDownloadCount sets the "download_count" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateDownloadCount() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldDownloadCount)
	return u
}

// AddDownloadCount adds v to the "download_count" field.
func (u *ItemVersionUpsert) AddDownloadCount(v int) *ItemVersionUpsert {
	u.Add(itemversion.FieldDownloadCount, v)
	return u
}

// SetReleasedAt sets the "released_at" field.
func (u *ItemVersionUpsert) SetReleasedAt(v time.Time) *ItemVersionUpsert {
	u.Set(itemversion.FieldReleasedAt, v)
	return u
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateReleasedAt() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldReleasedAt)
	return u
}

// SetConfigSchema sets the "config_schema" field.
func (u *ItemVersionUpsert) SetConfigSchema(v map[string]interface{}) *ItemVersionUpsert {
	u.Set(itemversion.FieldConfigSchema, v)
	return u
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateConfigSchema() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldConfigSchema)
	return u
}

// ClearConfigSchema clears the value of the "config_schema" field.
func (u *ItemVersionUpsert) ClearConfigSchema() *ItemVersionUpsert {
	u.SetNull(itemversion.FieldConfigSchema)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ItemVersionUpsert) SetCreatedAt(v time.Time) *ItemVersionUpsert {
	u.Set(itemversion.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateCreatedAt() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemVersionUpsert) SetUpdatedAt(v time.Time) *ItemVersionUpsert {
	u.Set(itemversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemVersionUpsert) UpdateUpdatedAt() *ItemVersionUpsert {
	u.SetExcluded(itemversion.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ItemVersionUpsertOne) UpdateNewValues() *ItemVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemVersionUpsertOne) Ignore() *ItemVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemVersionUpsertOne) DoNothing() *ItemVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemVersionCreate.OnConflict
// documentation for more info.
func (u *ItemVersionUpsertOne) Update(set func(*ItemVersionUpsert)) *ItemVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemVersionUpsertOne) SetItemID(v int) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateItemID() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateItemID()
	})
}

// SetVersion sets the "version" field.
func (u *ItemVersionUpsertOne) SetVersion(v string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateVersion() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetChangelog sets the "changelog" field.
func (u *ItemVersionUpsertOne) SetChangelog(v string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetChangelog(v)
	})
}

// UpdateChangelog sets the "changelog" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateChangelog() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateChangelog()
	})
}

// ClearChangelog clears the value of the "changelog" field.
func (u *ItemVersionUpsertOne) ClearChangelog() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearChangelog()
	})
}

// SetDownloadURL sets the "download_url" field.
func (u *ItemVersionUpsertOne) SetDownloadURL(v string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDownloadURL(v)
	})
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateDownloadURL() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDownloadURL()
	})
}

// ClearDownloadURL clears the value of the "download_url" field.
func (u *ItemVersionUpsertOne) ClearDownloadURL() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearDownloadURL()
	})
}

// SetManifestPath sets the "manifest_path" field.
func (u *ItemVersionUpsertOne) SetManifestPath(v string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetManifestPath(v)
	})
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateManifestPath() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateManifestPath()
	})
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *ItemVersionUpsertOne) ClearManifestPath() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearManifestPath()
	})
}

// SetMinSystemVersion sets the "min_system_version" field.
func (u *ItemVersionUpsertOne) SetMinSystemVersion(v string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetMinSystemVersion(v)
	})
}

// UpdateMinSystemVersion sets the "min_system_version" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateMinSystemVersion() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateMinSystemVersion()
	})
}

// ClearMinSystemVersion clears the value of the "min_system_version" field.
func (u *ItemVersionUpsertOne) ClearMinSystemVersion() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearMinSystemVersion()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *ItemVersionUpsertOne) SetDependencies(v map[string]string) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateDependencies() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ItemVersionUpsertOne) ClearDependencies() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearDependencies()
	})
}

// SetStatus sets the "status" field.
func (u *ItemVersionUpsertOne) SetStatus(v itemversion.Status) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateStatus() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetDownloadCount sets the "download_count" field.
func (u *ItemVersionUpsertOne) SetDownloadCount(v int) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDownloadCount(v)
	})
}

// AddDownloadCount adds v to the "download_count" field.
func (u *ItemVersionUpsertOne) AddDownloadCount(v int) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.AddDownloadCount(v)
	})
}

// UpdateDownloadCount sets the "download_count" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateDownloadCount() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDownloadCount()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *ItemVersionUpsertOne) SetReleasedAt(v time.Time) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateReleasedAt() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateReleasedAt()
	})
}

// SetConfigSchema sets the "config_schema" field.
func (u *ItemVersionUpsertOne) SetConfigSchema(v map[string]interface{}) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetConfigSchema(v)
	})
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateConfigSchema() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateConfigSchema()
	})
}

// ClearConfigSchema clears the value of the "config_schema" field.
func (u *ItemVersionUpsertOne) ClearConfigSchema() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearConfigSchema()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ItemVersionUpsertOne) SetCreatedAt(v time.Time) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateCreatedAt() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemVersionUpsertOne) SetUpdatedAt(v time.Time) *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemVersionUpsertOne) UpdateUpdatedAt() *ItemVersionUpsertOne {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ItemVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemVersionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemVersionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemVersionCreateBulk is the builder for creating many ItemVersion entities in bulk.
type ItemVersionCreateBulk struct {
	config
	err      error
	builders []*ItemVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the ItemVersion entities in the database.
func (_c *ItemVersionCreateBulk) Save(ctx context.Context) ([]*ItemVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemVersionCreateBulk) SaveX(ctx context.Context) []*ItemVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemVersionUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemVersionUpsertBulk {
	_c.conflict = opts
	return &ItemVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemVersionCreateBulk) OnConflictColumns(columns ...string) *ItemVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemVersionUpsertBulk{
		create: _c,
	}
}

// ItemVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of ItemVersion nodes.
type ItemVersionUpsertBulk struct {
	create *ItemVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ItemVersionUpsertBulk) UpdateNewValues() *ItemVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemVersionUpsertBulk) Ignore() *ItemVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemVersionUpsertBulk) DoNothing() *ItemVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemVersionCreateBulk.OnConflict
// documentation for more info.
func (u *ItemVersionUpsertBulk) Update(set func(*ItemVersionUpsert)) *ItemVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemVersionUpsertBulk) SetItemID(v int) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateItemID() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateItemID()
	})
}

// SetVersion sets the "version" field.
func (u *ItemVersionUpsertBulk) SetVersion(v string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateVersion() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateVersion()
	})
}

// SetChangelog sets the "changelog" field.
func (u *ItemVersionUpsertBulk) SetChangelog(v string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetChangelog(v)
	})
}

// UpdateChangelog sets the "changelog" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateChangelog() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateChangelog()
	})
}

// ClearChangelog clears the value of the "changelog" field.
func (u *ItemVersionUpsertBulk) ClearChangelog() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearChangelog()
	})
}

// SetDownloadURL sets the "download_url" field.
func (u *ItemVersionUpsertBulk) SetDownloadURL(v string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDownloadURL(v)
	})
}

// UpdateDownloadURL sets the "download_url" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateDownloadURL() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDownloadURL()
	})
}

// ClearDownloadURL clears the value of the "download_url" field.
func (u *ItemVersionUpsertBulk) ClearDownloadURL() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearDownloadURL()
	})
}

// SetManifestPath sets the "manifest_path" field.
func (u *ItemVersionUpsertBulk) SetManifestPath(v string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetManifestPath(v)
	})
}

// UpdateManifestPath sets the "manifest_path" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateManifestPath() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateManifestPath()
	})
}

// ClearManifestPath clears the value of the "manifest_path" field.
func (u *ItemVersionUpsertBulk) ClearManifestPath() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearManifestPath()
	})
}

// SetMinSystemVersion sets the "min_system_version" field.
func (u *ItemVersionUpsertBulk) SetMinSystemVersion(v string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetMinSystemVersion(v)
	})
}

// UpdateMinSystemVersion sets the "min_system_version" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateMinSystemVersion() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateMinSystemVersion()
	})
}

// ClearMinSystemVersion clears the value of the "min_system_version" field.
func (u *ItemVersionUpsertBulk) ClearMinSystemVersion() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearMinSystemVersion()
	})
}

// SetDependencies sets the "dependencies" field.
func (u *ItemVersionUpsertBulk) SetDependencies(v map[string]string) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDependencies(v)
	})
}

// UpdateDependencies sets the "dependencies" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateDependencies() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDependencies()
	})
}

// ClearDependencies clears the value of the "dependencies" field.
func (u *ItemVersionUpsertBulk) ClearDependencies() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearDependencies()
	})
}

// SetStatus sets the "status" field.
func (u *ItemVersionUpsertBulk) SetStatus(v itemversion.Status) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateStatus() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateStatus()
	})
}

// SetDownloadCount sets the "download_count" field.
func (u *ItemVersionUpsertBulk) SetDownloadCount(v int) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetDownloadCount(v)
	})
}

// AddDownloadCount adds v to the "download_count" field.
func (u *ItemVersionUpsertBulk) AddDownloadCount(v int) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.AddDownloadCount(v)
	})
}

// UpdateDownloadCount sets the "download_count" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateDownloadCount() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateDownloadCount()
	})
}

// SetReleasedAt sets the "released_at" field.
func (u *ItemVersionUpsertBulk) SetReleasedAt(v time.Time) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetReleasedAt(v)
	})
}

// UpdateReleasedAt sets the "released_at" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateReleasedAt() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateReleasedAt()
	})
}

// SetConfigSchema sets the "config_schema" field.
func (u *ItemVersionUpsertBulk) SetConfigSchema(v map[string]interface{}) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetConfigSchema(v)
	})
}

// UpdateConfigSchema sets the "config_schema" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateConfigSchema() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateConfigSchema()
	})
}

// ClearConfigSchema clears the value of the "config_schema" field.
func (u *ItemVersionUpsertBulk) ClearConfigSchema() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.ClearConfigSchema()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ItemVersionUpsertBulk) SetCreatedAt(v time.Time) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateCreatedAt() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemVersionUpsertBulk) SetUpdatedAt(v time.Time) *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemVersionUpsertBulk) UpdateUpdatedAt() *ItemVersionUpsertBulk {
	return u.Update(func(s *ItemVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ItemVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
