// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/change"
	"itsm-backend/ent/incident"
	"itsm-backend/ent/predicate"
	"itsm-backend/ent/problem"
	"itsm-backend/ent/ticket"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProblemUpdate is the builder for updating Problem entities.
type ProblemUpdate struct {
	config
	hooks    []Hook
	mutation *ProblemMutation
}

// Where appends a list predicates to the ProblemUpdate builder.
func (_u *ProblemUpdate) Where(ps ...predicate.Problem) *ProblemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRootCause sets the "root_cause" field.
func (_u *ProblemUpdate) SetRootCause(v string) *ProblemUpdate {
	_u.mutation.SetRootCause(v)
	return _u
}

// SetNillableRootCause sets the "root_cause" field if the given value is not nil.
func (_u *ProblemUpdate) SetNillableRootCause(v *string) *ProblemUpdate {
	if v != nil {
		_u.SetRootCause(*v)
	}
	return _u
}

// ClearRootCause clears the value of the "root_cause" field.
func (_u *ProblemUpdate) ClearRootCause() *ProblemUpdate {
	_u.mutation.ClearRootCause()
	return _u
}

// SetWorkaround sets the "workaround" field.
func (_u *ProblemUpdate) SetWorkaround(v string) *ProblemUpdate {
	_u.mutation.SetWorkaround(v)
	return _u
}

// SetNillableWorkaround sets the "workaround" field if the given value is not nil.
func (_u *ProblemUpdate) SetNillableWorkaround(v *string) *ProblemUpdate {
	if v != nil {
		_u.SetWorkaround(*v)
	}
	return _u
}

// ClearWorkaround clears the value of the "workaround" field.
func (_u *ProblemUpdate) ClearWorkaround() *ProblemUpdate {
	_u.mutation.ClearWorkaround()
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *ProblemUpdate) SetResolution(v string) *ProblemUpdate {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *ProblemUpdate) SetNillableResolution(v *string) *ProblemUpdate {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *ProblemUpdate) ClearResolution() *ProblemUpdate {
	_u.mutation.ClearResolution()
	return _u
}

// SetImpact sets the "impact" field.
func (_u *ProblemUpdate) SetImpact(v string) *ProblemUpdate {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *ProblemUpdate) SetNillableImpact(v *string) *ProblemUpdate {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// ClearImpact clears the value of the "impact" field.
func (_u *ProblemUpdate) ClearImpact() *ProblemUpdate {
	_u.mutation.ClearImpact()
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *ProblemUpdate) SetWorkItemID(v int) *ProblemUpdate {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *ProblemUpdate) SetNillableWorkItemID(v *int) *ProblemUpdate {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetWorkItem sets the "work_item" edge to the Ticket entity.
func (_u *ProblemUpdate) SetWorkItem(v *Ticket) *ProblemUpdate {
	return _u.SetWorkItemID(v.ID)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *ProblemUpdate) AddTicketIDs(ids ...int) *ProblemUpdate {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *ProblemUpdate) AddTickets(v ...*Ticket) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// AddIncidentIDs adds the "incidents" edge to the Incident entity by IDs.
func (_u *ProblemUpdate) AddIncidentIDs(ids ...int) *ProblemUpdate {
	_u.mutation.AddIncidentIDs(ids...)
	return _u
}

// AddIncidents adds the "incidents" edges to the Incident entity.
func (_u *ProblemUpdate) AddIncidents(v ...*Incident) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the Change entity by IDs.
func (_u *ProblemUpdate) AddChangeIDs(ids ...int) *ProblemUpdate {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the Change entity.
func (_u *ProblemUpdate) AddChanges(v ...*Change) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// Mutation returns the ProblemMutation object of the builder.
func (_u *ProblemUpdate) Mutation() *ProblemMutation {
	return _u.mutation
}

// ClearWorkItem clears the "work_item" edge to the Ticket entity.
func (_u *ProblemUpdate) ClearWorkItem() *ProblemUpdate {
	_u.mutation.ClearWorkItem()
	return _u
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *ProblemUpdate) ClearTickets() *ProblemUpdate {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *ProblemUpdate) RemoveTicketIDs(ids ...int) *ProblemUpdate {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *ProblemUpdate) RemoveTickets(v ...*Ticket) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// ClearIncidents clears all "incidents" edges to the Incident entity.
func (_u *ProblemUpdate) ClearIncidents() *ProblemUpdate {
	_u.mutation.ClearIncidents()
	return _u
}

// RemoveIncidentIDs removes the "incidents" edge to Incident entities by IDs.
func (_u *ProblemUpdate) RemoveIncidentIDs(ids ...int) *ProblemUpdate {
	_u.mutation.RemoveIncidentIDs(ids...)
	return _u
}

// RemoveIncidents removes "incidents" edges to Incident entities.
func (_u *ProblemUpdate) RemoveIncidents(v ...*Incident) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentIDs(ids...)
}

// ClearChanges clears all "changes" edges to the Change entity.
func (_u *ProblemUpdate) ClearChanges() *ProblemUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to Change entities by IDs.
func (_u *ProblemUpdate) RemoveChangeIDs(ids ...int) *ProblemUpdate {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to Change entities.
func (_u *ProblemUpdate) RemoveChanges(v ...*Change) *ProblemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProblemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProblemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemUpdate) check() error {
	if _u.mutation.WorkItemCleared() && len(_u.mutation.WorkItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Problem.work_item"`)
	}
	return nil
}

func (_u *ProblemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problem.Table, problem.Columns, sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(problem.FieldRootCause, field.TypeString, value)
	}
	if _u.mutation.RootCauseCleared() {
		_spec.ClearField(problem.FieldRootCause, field.TypeString)
	}
	if value, ok := _u.mutation.Workaround(); ok {
		_spec.SetField(problem.FieldWorkaround, field.TypeString, value)
	}
	if _u.mutation.WorkaroundCleared() {
		_spec.ClearField(problem.FieldWorkaround, field.TypeString)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(problem.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(problem.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(problem.FieldImpact, field.TypeString, value)
	}
	if _u.mutation.ImpactCleared() {
		_spec.ClearField(problem.FieldImpact, field.TypeString)
	}
	if _u.mutation.WorkItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   problem.WorkItemTable,
			Columns: []string{problem.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   problem.WorkItemTable,
			Columns: []string{problem.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentsIDs(); len(nodes) > 0 && !_u.mutation.IncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProblemUpdateOne is the builder for updating a single Problem entity.
type ProblemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProblemMutation
}

// SetRootCause sets the "root_cause" field.
func (_u *ProblemUpdateOne) SetRootCause(v string) *ProblemUpdateOne {
	_u.mutation.SetRootCause(v)
	return _u
}

// SetNillableRootCause sets the "root_cause" field if the given value is not nil.
func (_u *ProblemUpdateOne) SetNillableRootCause(v *string) *ProblemUpdateOne {
	if v != nil {
		_u.SetRootCause(*v)
	}
	return _u
}

// ClearRootCause clears the value of the "root_cause" field.
func (_u *ProblemUpdateOne) ClearRootCause() *ProblemUpdateOne {
	_u.mutation.ClearRootCause()
	return _u
}

// SetWorkaround sets the "workaround" field.
func (_u *ProblemUpdateOne) SetWorkaround(v string) *ProblemUpdateOne {
	_u.mutation.SetWorkaround(v)
	return _u
}

// SetNillableWorkaround sets the "workaround" field if the given value is not nil.
func (_u *ProblemUpdateOne) SetNillableWorkaround(v *string) *ProblemUpdateOne {
	if v != nil {
		_u.SetWorkaround(*v)
	}
	return _u
}

// ClearWorkaround clears the value of the "workaround" field.
func (_u *ProblemUpdateOne) ClearWorkaround() *ProblemUpdateOne {
	_u.mutation.ClearWorkaround()
	return _u
}

// SetResolution sets the "resolution" field.
func (_u *ProblemUpdateOne) SetResolution(v string) *ProblemUpdateOne {
	_u.mutation.SetResolution(v)
	return _u
}

// SetNillableResolution sets the "resolution" field if the given value is not nil.
func (_u *ProblemUpdateOne) SetNillableResolution(v *string) *ProblemUpdateOne {
	if v != nil {
		_u.SetResolution(*v)
	}
	return _u
}

// ClearResolution clears the value of the "resolution" field.
func (_u *ProblemUpdateOne) ClearResolution() *ProblemUpdateOne {
	_u.mutation.ClearResolution()
	return _u
}

// SetImpact sets the "impact" field.
func (_u *ProblemUpdateOne) SetImpact(v string) *ProblemUpdateOne {
	_u.mutation.SetImpact(v)
	return _u
}

// SetNillableImpact sets the "impact" field if the given value is not nil.
func (_u *ProblemUpdateOne) SetNillableImpact(v *string) *ProblemUpdateOne {
	if v != nil {
		_u.SetImpact(*v)
	}
	return _u
}

// ClearImpact clears the value of the "impact" field.
func (_u *ProblemUpdateOne) ClearImpact() *ProblemUpdateOne {
	_u.mutation.ClearImpact()
	return _u
}

// SetWorkItemID sets the "work_item_id" field.
func (_u *ProblemUpdateOne) SetWorkItemID(v int) *ProblemUpdateOne {
	_u.mutation.SetWorkItemID(v)
	return _u
}

// SetNillableWorkItemID sets the "work_item_id" field if the given value is not nil.
func (_u *ProblemUpdateOne) SetNillableWorkItemID(v *int) *ProblemUpdateOne {
	if v != nil {
		_u.SetWorkItemID(*v)
	}
	return _u
}

// SetWorkItem sets the "work_item" edge to the Ticket entity.
func (_u *ProblemUpdateOne) SetWorkItem(v *Ticket) *ProblemUpdateOne {
	return _u.SetWorkItemID(v.ID)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *ProblemUpdateOne) AddTicketIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *ProblemUpdateOne) AddTickets(v ...*Ticket) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// AddIncidentIDs adds the "incidents" edge to the Incident entity by IDs.
func (_u *ProblemUpdateOne) AddIncidentIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.AddIncidentIDs(ids...)
	return _u
}

// AddIncidents adds the "incidents" edges to the Incident entity.
func (_u *ProblemUpdateOne) AddIncidents(v ...*Incident) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIncidentIDs(ids...)
}

// AddChangeIDs adds the "changes" edge to the Change entity by IDs.
func (_u *ProblemUpdateOne) AddChangeIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.AddChangeIDs(ids...)
	return _u
}

// AddChanges adds the "changes" edges to the Change entity.
func (_u *ProblemUpdateOne) AddChanges(v ...*Change) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChangeIDs(ids...)
}

// Mutation returns the ProblemMutation object of the builder.
func (_u *ProblemUpdateOne) Mutation() *ProblemMutation {
	return _u.mutation
}

// ClearWorkItem clears the "work_item" edge to the Ticket entity.
func (_u *ProblemUpdateOne) ClearWorkItem() *ProblemUpdateOne {
	_u.mutation.ClearWorkItem()
	return _u
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *ProblemUpdateOne) ClearTickets() *ProblemUpdateOne {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *ProblemUpdateOne) RemoveTicketIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *ProblemUpdateOne) RemoveTickets(v ...*Ticket) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// ClearIncidents clears all "incidents" edges to the Incident entity.
func (_u *ProblemUpdateOne) ClearIncidents() *ProblemUpdateOne {
	_u.mutation.ClearIncidents()
	return _u
}

// RemoveIncidentIDs removes the "incidents" edge to Incident entities by IDs.
func (_u *ProblemUpdateOne) RemoveIncidentIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.RemoveIncidentIDs(ids...)
	return _u
}

// RemoveIncidents removes "incidents" edges to Incident entities.
func (_u *ProblemUpdateOne) RemoveIncidents(v ...*Incident) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIncidentIDs(ids...)
}

// ClearChanges clears all "changes" edges to the Change entity.
func (_u *ProblemUpdateOne) ClearChanges() *ProblemUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// RemoveChangeIDs removes the "changes" edge to Change entities by IDs.
func (_u *ProblemUpdateOne) RemoveChangeIDs(ids ...int) *ProblemUpdateOne {
	_u.mutation.RemoveChangeIDs(ids...)
	return _u
}

// RemoveChanges removes "changes" edges to Change entities.
func (_u *ProblemUpdateOne) RemoveChanges(v ...*Change) *ProblemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChangeIDs(ids...)
}

// Where appends a list predicates to the ProblemUpdate builder.
func (_u *ProblemUpdateOne) Where(ps ...predicate.Problem) *ProblemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProblemUpdateOne) Select(field string, fields ...string) *ProblemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Problem entity.
func (_u *ProblemUpdateOne) Save(ctx context.Context) (*Problem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProblemUpdateOne) SaveX(ctx context.Context) *Problem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProblemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProblemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProblemUpdateOne) check() error {
	if _u.mutation.WorkItemCleared() && len(_u.mutation.WorkItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Problem.work_item"`)
	}
	return nil
}

func (_u *ProblemUpdateOne) sqlSave(ctx context.Context) (_node *Problem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(problem.Table, problem.Columns, sqlgraph.NewFieldSpec(problem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Problem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, problem.FieldID)
		for _, f := range fields {
			if !problem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != problem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RootCause(); ok {
		_spec.SetField(problem.FieldRootCause, field.TypeString, value)
	}
	if _u.mutation.RootCauseCleared() {
		_spec.ClearField(problem.FieldRootCause, field.TypeString)
	}
	if value, ok := _u.mutation.Workaround(); ok {
		_spec.SetField(problem.FieldWorkaround, field.TypeString, value)
	}
	if _u.mutation.WorkaroundCleared() {
		_spec.ClearField(problem.FieldWorkaround, field.TypeString)
	}
	if value, ok := _u.mutation.Resolution(); ok {
		_spec.SetField(problem.FieldResolution, field.TypeString, value)
	}
	if _u.mutation.ResolutionCleared() {
		_spec.ClearField(problem.FieldResolution, field.TypeString)
	}
	if value, ok := _u.mutation.Impact(); ok {
		_spec.SetField(problem.FieldImpact, field.TypeString, value)
	}
	if _u.mutation.ImpactCleared() {
		_spec.ClearField(problem.FieldImpact, field.TypeString)
	}
	if _u.mutation.WorkItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   problem.WorkItemTable,
			Columns: []string{problem.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   problem.WorkItemTable,
			Columns: []string{problem.WorkItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   problem.TicketsTable,
			Columns: []string{problem.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIncidentsIDs(); len(nodes) > 0 && !_u.mutation.IncidentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IncidentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.IncidentsTable,
			Columns: problem.IncidentsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(incident.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChangesIDs(); len(nodes) > 0 && !_u.mutation.ChangesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChangesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   problem.ChangesTable,
			Columns: problem.ChangesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(change.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Problem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{problem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
