// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"itsm-backend/ent/processcallbackoutbox"
	"itsm-backend/internal/jsonvalue"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ProcessCallbackOutbox is the model entity for the ProcessCallbackOutbox schema.
type ProcessCallbackOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ExecutionKey holds the value of the "execution_key" field.
	ExecutionKey string `json:"execution_key,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int `json:"tenant_id,omitempty"`
	// ProcessInstanceID holds the value of the "process_instance_id" field.
	ProcessInstanceID int `json:"process_instance_id,omitempty"`
	// ProcessTaskID holds the value of the "process_task_id" field.
	ProcessTaskID int `json:"process_task_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID string `json:"task_id,omitempty"`
	// CallbackKind holds the value of the "callback_kind" field.
	CallbackKind string `json:"callback_kind,omitempty"`
	// HandlerID holds the value of the "handler_id" field.
	HandlerID string `json:"handler_id,omitempty"`
	// TaskType holds the value of the "task_type" field.
	TaskType string `json:"task_type,omitempty"`
	// ElementID holds the value of the "element_id" field.
	ElementID string `json:"element_id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// 可信连接器配置引用；端点和凭据在执行时解析，绝不持久化到回调载荷
	ConfigRef string `json:"config_ref,omitempty"`
	// 按处理器声明字段过滤后的非敏感业务载荷
	Variables jsonvalue.NumberMap `json:"variables,omitempty"`
	// OptionalDeclared holds the value of the "optional_declared" field.
	OptionalDeclared bool `json:"optional_declared,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// LeaseOwner holds the value of the "lease_owner" field.
	LeaseOwner string `json:"lease_owner,omitempty"`
	// LeaseExpiresAt holds the value of the "lease_expires_at" field.
	LeaseExpiresAt time.Time `json:"lease_expires_at,omitempty"`
	// LastErrorClass holds the value of the "last_error_class" field.
	LastErrorClass string `json:"last_error_class,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt time.Time `json:"completed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProcessCallbackOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case processcallbackoutbox.FieldVariables:
			values[i] = new([]byte)
		case processcallbackoutbox.FieldOptionalDeclared:
			values[i] = new(sql.NullBool)
		case processcallbackoutbox.FieldID, processcallbackoutbox.FieldTenantID, processcallbackoutbox.FieldProcessInstanceID, processcallbackoutbox.FieldProcessTaskID, processcallbackoutbox.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case processcallbackoutbox.FieldExecutionKey, processcallbackoutbox.FieldTaskID, processcallbackoutbox.FieldCallbackKind, processcallbackoutbox.FieldHandlerID, processcallbackoutbox.FieldTaskType, processcallbackoutbox.FieldElementID, processcallbackoutbox.FieldAction, processcallbackoutbox.FieldConfigRef, processcallbackoutbox.FieldStatus, processcallbackoutbox.FieldLeaseOwner, processcallbackoutbox.FieldLastErrorClass:
			values[i] = new(sql.NullString)
		case processcallbackoutbox.FieldNextAttemptAt, processcallbackoutbox.FieldLeaseExpiresAt, processcallbackoutbox.FieldCompletedAt, processcallbackoutbox.FieldCreatedAt, processcallbackoutbox.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProcessCallbackOutbox fields.
func (_m *ProcessCallbackOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case processcallbackoutbox.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case processcallbackoutbox.FieldExecutionKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_key", values[i])
			} else if value.Valid {
				_m.ExecutionKey = value.String
			}
		case processcallbackoutbox.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = int(value.Int64)
			}
		case processcallbackoutbox.FieldProcessInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field process_instance_id", values[i])
			} else if value.Valid {
				_m.ProcessInstanceID = int(value.Int64)
			}
		case processcallbackoutbox.FieldProcessTaskID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field process_task_id", values[i])
			} else if value.Valid {
				_m.ProcessTaskID = int(value.Int64)
			}
		case processcallbackoutbox.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case processcallbackoutbox.FieldCallbackKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_kind", values[i])
			} else if value.Valid {
				_m.CallbackKind = value.String
			}
		case processcallbackoutbox.FieldHandlerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field handler_id", values[i])
			} else if value.Valid {
				_m.HandlerID = value.String
			}
		case processcallbackoutbox.FieldTaskType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_type", values[i])
			} else if value.Valid {
				_m.TaskType = value.String
			}
		case processcallbackoutbox.FieldElementID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field element_id", values[i])
			} else if value.Valid {
				_m.ElementID = value.String
			}
		case processcallbackoutbox.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case processcallbackoutbox.FieldConfigRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_ref", values[i])
			} else if value.Valid {
				_m.ConfigRef = value.String
			}
		case processcallbackoutbox.FieldVariables:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field variables", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Variables); err != nil {
					return fmt.Errorf("unmarshal field variables: %w", err)
				}
			}
		case processcallbackoutbox.FieldOptionalDeclared:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field optional_declared", values[i])
			} else if value.Valid {
				_m.OptionalDeclared = value.Bool
			}
		case processcallbackoutbox.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case processcallbackoutbox.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case processcallbackoutbox.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case processcallbackoutbox.FieldLeaseOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field lease_owner", values[i])
			} else if value.Valid {
				_m.LeaseOwner = value.String
			}
		case processcallbackoutbox.FieldLeaseExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lease_expires_at", values[i])
			} else if value.Valid {
				_m.LeaseExpiresAt = value.Time
			}
		case processcallbackoutbox.FieldLastErrorClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_class", values[i])
			} else if value.Valid {
				_m.LastErrorClass = value.String
			}
		case processcallbackoutbox.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = value.Time
			}
		case processcallbackoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case processcallbackoutbox.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProcessCallbackOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *ProcessCallbackOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProcessCallbackOutbox.
// Note that you need to call ProcessCallbackOutbox.Unwrap() before calling this method if this ProcessCallbackOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProcessCallbackOutbox) Update() *ProcessCallbackOutboxUpdateOne {
	return NewProcessCallbackOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProcessCallbackOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProcessCallbackOutbox) Unwrap() *ProcessCallbackOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProcessCallbackOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProcessCallbackOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("ProcessCallbackOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("execution_key=")
	builder.WriteString(_m.ExecutionKey)
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("process_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessInstanceID))
	builder.WriteString(", ")
	builder.WriteString("process_task_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProcessTaskID))
	builder.WriteString(", ")
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("callback_kind=")
	builder.WriteString(_m.CallbackKind)
	builder.WriteString(", ")
	builder.WriteString("handler_id=")
	builder.WriteString(_m.HandlerID)
	builder.WriteString(", ")
	builder.WriteString("task_type=")
	builder.WriteString(_m.TaskType)
	builder.WriteString(", ")
	builder.WriteString("element_id=")
	builder.WriteString(_m.ElementID)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("config_ref=")
	builder.WriteString(_m.ConfigRef)
	builder.WriteString(", ")
	builder.WriteString("variables=")
	builder.WriteString(fmt.Sprintf("%v", _m.Variables))
	builder.WriteString(", ")
	builder.WriteString("optional_declared=")
	builder.WriteString(fmt.Sprintf("%v", _m.OptionalDeclared))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("lease_owner=")
	builder.WriteString(_m.LeaseOwner)
	builder.WriteString(", ")
	builder.WriteString("lease_expires_at=")
	builder.WriteString(_m.LeaseExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_error_class=")
	builder.WriteString(_m.LastErrorClass)
	builder.WriteString(", ")
	builder.WriteString("completed_at=")
	builder.WriteString(_m.CompletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProcessCallbackOutboxes is a parsable slice of ProcessCallbackOutbox.
type ProcessCallbackOutboxes []*ProcessCallbackOutbox
