// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/processdefinition"
	"itsm-backend/ent/processdeployment"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProcessDeploymentCreate is the builder for creating a ProcessDeployment entity.
type ProcessDeploymentCreate struct {
	config
	mutation *ProcessDeploymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeploymentID sets the "deployment_id" field.
func (_c *ProcessDeploymentCreate) SetDeploymentID(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentID(v)
	return _c
}

// SetDeploymentName sets the "deployment_name" field.
func (_c *ProcessDeploymentCreate) SetDeploymentName(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentName(v)
	return _c
}

// SetDeploymentSource sets the "deployment_source" field.
func (_c *ProcessDeploymentCreate) SetDeploymentSource(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentSource(v)
	return _c
}

// SetNillableDeploymentSource sets the "deployment_source" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableDeploymentSource(v *string) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetDeploymentSource(*v)
	}
	return _c
}

// SetDeploymentTime sets the "deployment_time" field.
func (_c *ProcessDeploymentCreate) SetDeploymentTime(v time.Time) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentTime(v)
	return _c
}

// SetNillableDeploymentTime sets the "deployment_time" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableDeploymentTime(v *time.Time) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetDeploymentTime(*v)
	}
	return _c
}

// SetDeployedBy sets the "deployed_by" field.
func (_c *ProcessDeploymentCreate) SetDeployedBy(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeployedBy(v)
	return _c
}

// SetNillableDeployedBy sets the "deployed_by" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableDeployedBy(v *string) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetDeployedBy(*v)
	}
	return _c
}

// SetDeploymentComment sets the "deployment_comment" field.
func (_c *ProcessDeploymentCreate) SetDeploymentComment(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentComment(v)
	return _c
}

// SetNillableDeploymentComment sets the "deployment_comment" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableDeploymentComment(v *string) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetDeploymentComment(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ProcessDeploymentCreate) SetIsActive(v bool) *ProcessDeploymentCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableIsActive(v *bool) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetDeploymentCategory sets the "deployment_category" field.
func (_c *ProcessDeploymentCreate) SetDeploymentCategory(v string) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentCategory(v)
	return _c
}

// SetNillableDeploymentCategory sets the "deployment_category" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableDeploymentCategory(v *string) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetDeploymentCategory(*v)
	}
	return _c
}

// SetDeploymentMetadata sets the "deployment_metadata" field.
func (_c *ProcessDeploymentCreate) SetDeploymentMetadata(v map[string]interface{}) *ProcessDeploymentCreate {
	_c.mutation.SetDeploymentMetadata(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ProcessDeploymentCreate) SetTenantID(v int) *ProcessDeploymentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProcessDeploymentCreate) SetCreatedAt(v time.Time) *ProcessDeploymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableCreatedAt(v *time.Time) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ProcessDeploymentCreate) SetUpdatedAt(v time.Time) *ProcessDeploymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ProcessDeploymentCreate) SetNillableUpdatedAt(v *time.Time) *ProcessDeploymentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddDefinitionIDs adds the "definitions" edge to the ProcessDefinition entity by IDs.
func (_c *ProcessDeploymentCreate) AddDefinitionIDs(ids ...int) *ProcessDeploymentCreate {
	_c.mutation.AddDefinitionIDs(ids...)
	return _c
}

// AddDefinitions adds the "definitions" edges to the ProcessDefinition entity.
func (_c *ProcessDeploymentCreate) AddDefinitions(v ...*ProcessDefinition) *ProcessDeploymentCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDefinitionIDs(ids...)
}

// Mutation returns the ProcessDeploymentMutation object of the builder.
func (_c *ProcessDeploymentCreate) Mutation() *ProcessDeploymentMutation {
	return _c.mutation
}

// Save creates the ProcessDeployment in the database.
func (_c *ProcessDeploymentCreate) Save(ctx context.Context) (*ProcessDeployment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProcessDeploymentCreate) SaveX(ctx context.Context) *ProcessDeployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessDeploymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessDeploymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProcessDeploymentCreate) defaults() {
	if _, ok := _c.mutation.DeploymentTime(); !ok {
		v := processdeployment.DefaultDeploymentTime()
		_c.mutation.SetDeploymentTime(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := processdeployment.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.DeploymentCategory(); !ok {
		v := processdeployment.DefaultDeploymentCategory
		_c.mutation.SetDeploymentCategory(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := processdeployment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := processdeployment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProcessDeploymentCreate) check() error {
	if _, ok := _c.mutation.DeploymentID(); !ok {
		return &ValidationError{Name: "deployment_id", err: errors.New(`ent: missing required field "ProcessDeployment.deployment_id"`)}
	}
	if v, ok := _c.mutation.DeploymentID(); ok {
		if err := processdeployment.DeploymentIDValidator(v); err != nil {
			return &ValidationError{Name: "deployment_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDeployment.deployment_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeploymentName(); !ok {
		return &ValidationError{Name: "deployment_name", err: errors.New(`ent: missing required field "ProcessDeployment.deployment_name"`)}
	}
	if v, ok := _c.mutation.DeploymentName(); ok {
		if err := processdeployment.DeploymentNameValidator(v); err != nil {
			return &ValidationError{Name: "deployment_name", err: fmt.Errorf(`ent: validator failed for field "ProcessDeployment.deployment_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DeploymentTime(); !ok {
		return &ValidationError{Name: "deployment_time", err: errors.New(`ent: missing required field "ProcessDeployment.deployment_time"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ProcessDeployment.is_active"`)}
	}
	if _, ok := _c.mutation.DeploymentCategory(); !ok {
		return &ValidationError{Name: "deployment_category", err: errors.New(`ent: missing required field "ProcessDeployment.deployment_category"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ProcessDeployment.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := processdeployment.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "ProcessDeployment.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProcessDeployment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ProcessDeployment.updated_at"`)}
	}
	return nil
}

func (_c *ProcessDeploymentCreate) sqlSave(ctx context.Context) (*ProcessDeployment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProcessDeploymentCreate) createSpec() (*ProcessDeployment, *sqlgraph.CreateSpec) {
	var (
		_node = &ProcessDeployment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(processdeployment.Table, sqlgraph.NewFieldSpec(processdeployment.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DeploymentID(); ok {
		_spec.SetField(processdeployment.FieldDeploymentID, field.TypeString, value)
		_node.DeploymentID = value
	}
	if value, ok := _c.mutation.DeploymentName(); ok {
		_spec.SetField(processdeployment.FieldDeploymentName, field.TypeString, value)
		_node.DeploymentName = value
	}
	if value, ok := _c.mutation.DeploymentSource(); ok {
		_spec.SetField(processdeployment.FieldDeploymentSource, field.TypeString, value)
		_node.DeploymentSource = value
	}
	if value, ok := _c.mutation.DeploymentTime(); ok {
		_spec.SetField(processdeployment.FieldDeploymentTime, field.TypeTime, value)
		_node.DeploymentTime = value
	}
	if value, ok := _c.mutation.DeployedBy(); ok {
		_spec.SetField(processdeployment.FieldDeployedBy, field.TypeString, value)
		_node.DeployedBy = value
	}
	if value, ok := _c.mutation.DeploymentComment(); ok {
		_spec.SetField(processdeployment.FieldDeploymentComment, field.TypeString, value)
		_node.DeploymentComment = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(processdeployment.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.DeploymentCategory(); ok {
		_spec.SetField(processdeployment.FieldDeploymentCategory, field.TypeString, value)
		_node.DeploymentCategory = value
	}
	if value, ok := _c.mutation.DeploymentMetadata(); ok {
		_spec.SetField(processdeployment.FieldDeploymentMetadata, field.TypeJSON, value)
		_node.DeploymentMetadata = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(processdeployment.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(processdeployment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(processdeployment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DefinitionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   processdeployment.DefinitionsTable,
			Columns: []string{processdeployment.DefinitionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(processdefinition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProcessDeployment.Create().
//		SetDeploymentID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProcessDeploymentUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProcessDeploymentCreate) OnConflict(opts ...sql.ConflictOption) *ProcessDeploymentUpsertOne {
	_c.conflict = opts
	return &ProcessDeploymentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProcessDeploymentCreate) OnConflictColumns(columns ...string) *ProcessDeploymentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProcessDeploymentUpsertOne{
		create: _c,
	}
}

type (
	// ProcessDeploymentUpsertOne is the builder for "upsert"-ing
	//  one ProcessDeployment node.
	ProcessDeploymentUpsertOne struct {
		create *ProcessDeploymentCreate
	}

	// ProcessDeploymentUpsert is the "OnConflict" setter.
	ProcessDeploymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeploymentID sets the "deployment_id" field.
func (u *ProcessDeploymentUpsert) SetDeploymentID(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentID, v)
	return u
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentID() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentID)
	return u
}

// SetDeploymentName sets the "deployment_name" field.
func (u *ProcessDeploymentUpsert) SetDeploymentName(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentName, v)
	return u
}

// UpdateDeploymentName sets the "deployment_name" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentName() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentName)
	return u
}

// SetDeploymentSource sets the "deployment_source" field.
func (u *ProcessDeploymentUpsert) SetDeploymentSource(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentSource, v)
	return u
}

// UpdateDeploymentSource sets the "deployment_source" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentSource() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentSource)
	return u
}

// ClearDeploymentSource clears the value of the "deployment_source" field.
func (u *ProcessDeploymentUpsert) ClearDeploymentSource() *ProcessDeploymentUpsert {
	u.SetNull(processdeployment.FieldDeploymentSource)
	return u
}

// SetDeploymentTime sets the "deployment_time" field.
func (u *ProcessDeploymentUpsert) SetDeploymentTime(v time.Time) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentTime, v)
	return u
}

// UpdateDeploymentTime sets the "deployment_time" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentTime() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentTime)
	return u
}

// SetDeployedBy sets the "deployed_by" field.
func (u *ProcessDeploymentUpsert) SetDeployedBy(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeployedBy, v)
	return u
}

// UpdateDeployedBy sets the "deployed_by" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeployedBy() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeployedBy)
	return u
}

// ClearDeployedBy clears the value of the "deployed_by" field.
func (u *ProcessDeploymentUpsert) ClearDeployedBy() *ProcessDeploymentUpsert {
	u.SetNull(processdeployment.FieldDeployedBy)
	return u
}

// SetDeploymentComment sets the "deployment_comment" field.
func (u *ProcessDeploymentUpsert) SetDeploymentComment(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentComment, v)
	return u
}

// UpdateDeploymentComment sets the "deployment_comment" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentComment() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentComment)
	return u
}

// ClearDeploymentComment clears the value of the "deployment_comment" field.
func (u *ProcessDeploymentUpsert) ClearDeploymentComment() *ProcessDeploymentUpsert {
	u.SetNull(processdeployment.FieldDeploymentComment)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *ProcessDeploymentUpsert) SetIsActive(v bool) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateIsActive() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldIsActive)
	return u
}

// SetDeploymentCategory sets the "deployment_category" field.
func (u *ProcessDeploymentUpsert) SetDeploymentCategory(v string) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentCategory, v)
	return u
}

// UpdateDeploymentCategory sets the "deployment_category" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentCategory() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentCategory)
	return u
}

// SetDeploymentMetadata sets the "deployment_metadata" field.
func (u *ProcessDeploymentUpsert) SetDeploymentMetadata(v map[string]interface{}) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldDeploymentMetadata, v)
	return u
}

// UpdateDeploymentMetadata sets the "deployment_metadata" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateDeploymentMetadata() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldDeploymentMetadata)
	return u
}

// ClearDeploymentMetadata clears the value of the "deployment_metadata" field.
func (u *ProcessDeploymentUpsert) ClearDeploymentMetadata() *ProcessDeploymentUpsert {
	u.SetNull(processdeployment.FieldDeploymentMetadata)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *ProcessDeploymentUpsert) SetTenantID(v int) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateTenantID() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *ProcessDeploymentUpsert) AddTenantID(v int) *ProcessDeploymentUpsert {
	u.Add(processdeployment.FieldTenantID, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ProcessDeploymentUpsert) SetCreatedAt(v time.Time) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateCreatedAt() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcessDeploymentUpsert) SetUpdatedAt(v time.Time) *ProcessDeploymentUpsert {
	u.Set(processdeployment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsert) UpdateUpdatedAt() *ProcessDeploymentUpsert {
	u.SetExcluded(processdeployment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProcessDeploymentUpsertOne) UpdateNewValues() *ProcessDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProcessDeploymentUpsertOne) Ignore() *ProcessDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProcessDeploymentUpsertOne) DoNothing() *ProcessDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProcessDeploymentCreate.OnConflict
// documentation for more info.
func (u *ProcessDeploymentUpsertOne) Update(set func(*ProcessDeploymentUpsert)) *ProcessDeploymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProcessDeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentID(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentID() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetDeploymentName sets the "deployment_name" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentName(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentName(v)
	})
}

// UpdateDeploymentName sets the "deployment_name" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentName() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentName()
	})
}

// SetDeploymentSource sets the "deployment_source" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentSource(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentSource(v)
	})
}

// UpdateDeploymentSource sets the "deployment_source" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentSource() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentSource()
	})
}

// ClearDeploymentSource clears the value of the "deployment_source" field.
func (u *ProcessDeploymentUpsertOne) ClearDeploymentSource() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentSource()
	})
}

// SetDeploymentTime sets the "deployment_time" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentTime(v time.Time) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentTime(v)
	})
}

// UpdateDeploymentTime sets the "deployment_time" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentTime() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentTime()
	})
}

// SetDeployedBy sets the "deployed_by" field.
func (u *ProcessDeploymentUpsertOne) SetDeployedBy(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeployedBy(v)
	})
}

// UpdateDeployedBy sets the "deployed_by" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeployedBy() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeployedBy()
	})
}

// ClearDeployedBy clears the value of the "deployed_by" field.
func (u *ProcessDeploymentUpsertOne) ClearDeployedBy() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeployedBy()
	})
}

// SetDeploymentComment sets the "deployment_comment" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentComment(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentComment(v)
	})
}

// UpdateDeploymentComment sets the "deployment_comment" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentComment() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentComment()
	})
}

// ClearDeploymentComment clears the value of the "deployment_comment" field.
func (u *ProcessDeploymentUpsertOne) ClearDeploymentComment() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentComment()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ProcessDeploymentUpsertOne) SetIsActive(v bool) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateIsActive() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateIsActive()
	})
}

// SetDeploymentCategory sets the "deployment_category" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentCategory(v string) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentCategory(v)
	})
}

// UpdateDeploymentCategory sets the "deployment_category" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentCategory() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentCategory()
	})
}

// SetDeploymentMetadata sets the "deployment_metadata" field.
func (u *ProcessDeploymentUpsertOne) SetDeploymentMetadata(v map[string]interface{}) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentMetadata(v)
	})
}

// UpdateDeploymentMetadata sets the "deployment_metadata" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateDeploymentMetadata() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentMetadata()
	})
}

// ClearDeploymentMetadata clears the value of the "deployment_metadata" field.
func (u *ProcessDeploymentUpsertOne) ClearDeploymentMetadata() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentMetadata()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *ProcessDeploymentUpsertOne) SetTenantID(v int) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *ProcessDeploymentUpsertOne) AddTenantID(v int) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateTenantID() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateTenantID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ProcessDeploymentUpsertOne) SetCreatedAt(v time.Time) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateCreatedAt() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcessDeploymentUpsertOne) SetUpdatedAt(v time.Time) *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertOne) UpdateUpdatedAt() *ProcessDeploymentUpsertOne {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProcessDeploymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProcessDeploymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProcessDeploymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProcessDeploymentUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProcessDeploymentUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProcessDeploymentCreateBulk is the builder for creating many ProcessDeployment entities in bulk.
type ProcessDeploymentCreateBulk struct {
	config
	err      error
	builders []*ProcessDeploymentCreate
	conflict []sql.ConflictOption
}

// Save creates the ProcessDeployment entities in the database.
func (_c *ProcessDeploymentCreateBulk) Save(ctx context.Context) ([]*ProcessDeployment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProcessDeployment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProcessDeploymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProcessDeploymentCreateBulk) SaveX(ctx context.Context) []*ProcessDeployment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProcessDeploymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProcessDeploymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProcessDeployment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProcessDeploymentUpsert) {
//			SetDeploymentID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProcessDeploymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProcessDeploymentUpsertBulk {
	_c.conflict = opts
	return &ProcessDeploymentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProcessDeploymentCreateBulk) OnConflictColumns(columns ...string) *ProcessDeploymentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProcessDeploymentUpsertBulk{
		create: _c,
	}
}

// ProcessDeploymentUpsertBulk is the builder for "upsert"-ing
// a bulk of ProcessDeployment nodes.
type ProcessDeploymentUpsertBulk struct {
	create *ProcessDeploymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProcessDeploymentUpsertBulk) UpdateNewValues() *ProcessDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProcessDeployment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProcessDeploymentUpsertBulk) Ignore() *ProcessDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProcessDeploymentUpsertBulk) DoNothing() *ProcessDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProcessDeploymentCreateBulk.OnConflict
// documentation for more info.
func (u *ProcessDeploymentUpsertBulk) Update(set func(*ProcessDeploymentUpsert)) *ProcessDeploymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProcessDeploymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeploymentID sets the "deployment_id" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentID(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentID(v)
	})
}

// UpdateDeploymentID sets the "deployment_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentID() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentID()
	})
}

// SetDeploymentName sets the "deployment_name" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentName(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentName(v)
	})
}

// UpdateDeploymentName sets the "deployment_name" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentName() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentName()
	})
}

// SetDeploymentSource sets the "deployment_source" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentSource(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentSource(v)
	})
}

// UpdateDeploymentSource sets the "deployment_source" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentSource() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentSource()
	})
}

// ClearDeploymentSource clears the value of the "deployment_source" field.
func (u *ProcessDeploymentUpsertBulk) ClearDeploymentSource() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentSource()
	})
}

// SetDeploymentTime sets the "deployment_time" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentTime(v time.Time) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentTime(v)
	})
}

// UpdateDeploymentTime sets the "deployment_time" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentTime() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentTime()
	})
}

// SetDeployedBy sets the "deployed_by" field.
func (u *ProcessDeploymentUpsertBulk) SetDeployedBy(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeployedBy(v)
	})
}

// UpdateDeployedBy sets the "deployed_by" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeployedBy() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeployedBy()
	})
}

// ClearDeployedBy clears the value of the "deployed_by" field.
func (u *ProcessDeploymentUpsertBulk) ClearDeployedBy() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeployedBy()
	})
}

// SetDeploymentComment sets the "deployment_comment" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentComment(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentComment(v)
	})
}

// UpdateDeploymentComment sets the "deployment_comment" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentComment() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentComment()
	})
}

// ClearDeploymentComment clears the value of the "deployment_comment" field.
func (u *ProcessDeploymentUpsertBulk) ClearDeploymentComment() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentComment()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ProcessDeploymentUpsertBulk) SetIsActive(v bool) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateIsActive() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateIsActive()
	})
}

// SetDeploymentCategory sets the "deployment_category" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentCategory(v string) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentCategory(v)
	})
}

// UpdateDeploymentCategory sets the "deployment_category" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentCategory() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentCategory()
	})
}

// SetDeploymentMetadata sets the "deployment_metadata" field.
func (u *ProcessDeploymentUpsertBulk) SetDeploymentMetadata(v map[string]interface{}) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetDeploymentMetadata(v)
	})
}

// UpdateDeploymentMetadata sets the "deployment_metadata" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateDeploymentMetadata() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateDeploymentMetadata()
	})
}

// ClearDeploymentMetadata clears the value of the "deployment_metadata" field.
func (u *ProcessDeploymentUpsertBulk) ClearDeploymentMetadata() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.ClearDeploymentMetadata()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *ProcessDeploymentUpsertBulk) SetTenantID(v int) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *ProcessDeploymentUpsertBulk) AddTenantID(v int) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateTenantID() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateTenantID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ProcessDeploymentUpsertBulk) SetCreatedAt(v time.Time) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateCreatedAt() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ProcessDeploymentUpsertBulk) SetUpdatedAt(v time.Time) *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ProcessDeploymentUpsertBulk) UpdateUpdatedAt() *ProcessDeploymentUpsertBulk {
	return u.Update(func(s *ProcessDeploymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ProcessDeploymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProcessDeploymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProcessDeploymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProcessDeploymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
