// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"itsm-backend/ent/slaalertrule"
	"itsm-backend/ent/sladefinition"
	"itsm-backend/ent/slametric"
	"itsm-backend/ent/slaviolation"
	"itsm-backend/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SLADefinitionCreate is the builder for creating a SLADefinition entity.
type SLADefinitionCreate struct {
	config
	mutation *SLADefinitionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *SLADefinitionCreate) SetName(v string) *SLADefinitionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SLADefinitionCreate) SetDescription(v string) *SLADefinitionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableDescription(v *string) *SLADefinitionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetServiceType sets the "service_type" field.
func (_c *SLADefinitionCreate) SetServiceType(v string) *SLADefinitionCreate {
	_c.mutation.SetServiceType(v)
	return _c
}

// SetNillableServiceType sets the "service_type" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableServiceType(v *string) *SLADefinitionCreate {
	if v != nil {
		_c.SetServiceType(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SLADefinitionCreate) SetPriority(v string) *SLADefinitionCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillablePriority(v *string) *SLADefinitionCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCategoryIds sets the "category_ids" field.
func (_c *SLADefinitionCreate) SetCategoryIds(v []int) *SLADefinitionCreate {
	_c.mutation.SetCategoryIds(v)
	return _c
}

// SetResponseTime sets the "response_time" field.
func (_c *SLADefinitionCreate) SetResponseTime(v int) *SLADefinitionCreate {
	_c.mutation.SetResponseTime(v)
	return _c
}

// SetNillableResponseTime sets the "response_time" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableResponseTime(v *int) *SLADefinitionCreate {
	if v != nil {
		_c.SetResponseTime(*v)
	}
	return _c
}

// SetResolutionTime sets the "resolution_time" field.
func (_c *SLADefinitionCreate) SetResolutionTime(v int) *SLADefinitionCreate {
	_c.mutation.SetResolutionTime(v)
	return _c
}

// SetNillableResolutionTime sets the "resolution_time" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableResolutionTime(v *int) *SLADefinitionCreate {
	if v != nil {
		_c.SetResolutionTime(*v)
	}
	return _c
}

// SetBusinessHours sets the "business_hours" field.
func (_c *SLADefinitionCreate) SetBusinessHours(v map[string]interface{}) *SLADefinitionCreate {
	_c.mutation.SetBusinessHours(v)
	return _c
}

// SetEscalationRules sets the "escalation_rules" field.
func (_c *SLADefinitionCreate) SetEscalationRules(v map[string]interface{}) *SLADefinitionCreate {
	_c.mutation.SetEscalationRules(v)
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *SLADefinitionCreate) SetConditions(v map[string]interface{}) *SLADefinitionCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetExcludeWeekends sets the "exclude_weekends" field.
func (_c *SLADefinitionCreate) SetExcludeWeekends(v bool) *SLADefinitionCreate {
	_c.mutation.SetExcludeWeekends(v)
	return _c
}

// SetNillableExcludeWeekends sets the "exclude_weekends" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableExcludeWeekends(v *bool) *SLADefinitionCreate {
	if v != nil {
		_c.SetExcludeWeekends(*v)
	}
	return _c
}

// SetExcludeHolidays sets the "exclude_holidays" field.
func (_c *SLADefinitionCreate) SetExcludeHolidays(v bool) *SLADefinitionCreate {
	_c.mutation.SetExcludeHolidays(v)
	return _c
}

// SetNillableExcludeHolidays sets the "exclude_holidays" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableExcludeHolidays(v *bool) *SLADefinitionCreate {
	if v != nil {
		_c.SetExcludeHolidays(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *SLADefinitionCreate) SetIsActive(v bool) *SLADefinitionCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableIsActive(v *bool) *SLADefinitionCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SLADefinitionCreate) SetTenantID(v int) *SLADefinitionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SLADefinitionCreate) SetCreatedAt(v time.Time) *SLADefinitionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableCreatedAt(v *time.Time) *SLADefinitionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SLADefinitionCreate) SetUpdatedAt(v time.Time) *SLADefinitionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SLADefinitionCreate) SetNillableUpdatedAt(v *time.Time) *SLADefinitionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddViolationIDs adds the "violations" edge to the SLAViolation entity by IDs.
func (_c *SLADefinitionCreate) AddViolationIDs(ids ...int) *SLADefinitionCreate {
	_c.mutation.AddViolationIDs(ids...)
	return _c
}

// AddViolations adds the "violations" edges to the SLAViolation entity.
func (_c *SLADefinitionCreate) AddViolations(v ...*SLAViolation) *SLADefinitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddViolationIDs(ids...)
}

// AddMetricIDs adds the "metrics" edge to the SLAMetric entity by IDs.
func (_c *SLADefinitionCreate) AddMetricIDs(ids ...int) *SLADefinitionCreate {
	_c.mutation.AddMetricIDs(ids...)
	return _c
}

// AddMetrics adds the "metrics" edges to the SLAMetric entity.
func (_c *SLADefinitionCreate) AddMetrics(v ...*SLAMetric) *SLADefinitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMetricIDs(ids...)
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *SLADefinitionCreate) AddTicketIDs(ids ...int) *SLADefinitionCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *SLADefinitionCreate) AddTickets(v ...*Ticket) *SLADefinitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// AddAlertRuleIDs adds the "alert_rules" edge to the SLAAlertRule entity by IDs.
func (_c *SLADefinitionCreate) AddAlertRuleIDs(ids ...int) *SLADefinitionCreate {
	_c.mutation.AddAlertRuleIDs(ids...)
	return _c
}

// AddAlertRules adds the "alert_rules" edges to the SLAAlertRule entity.
func (_c *SLADefinitionCreate) AddAlertRules(v ...*SLAAlertRule) *SLADefinitionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAlertRuleIDs(ids...)
}

// Mutation returns the SLADefinitionMutation object of the builder.
func (_c *SLADefinitionCreate) Mutation() *SLADefinitionMutation {
	return _c.mutation
}

// Save creates the SLADefinition in the database.
func (_c *SLADefinitionCreate) Save(ctx context.Context) (*SLADefinition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SLADefinitionCreate) SaveX(ctx context.Context) *SLADefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SLADefinitionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SLADefinitionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SLADefinitionCreate) defaults() {
	if _, ok := _c.mutation.ResponseTime(); !ok {
		v := sladefinition.DefaultResponseTime
		_c.mutation.SetResponseTime(v)
	}
	if _, ok := _c.mutation.ResolutionTime(); !ok {
		v := sladefinition.DefaultResolutionTime
		_c.mutation.SetResolutionTime(v)
	}
	if _, ok := _c.mutation.ExcludeWeekends(); !ok {
		v := sladefinition.DefaultExcludeWeekends
		_c.mutation.SetExcludeWeekends(v)
	}
	if _, ok := _c.mutation.ExcludeHolidays(); !ok {
		v := sladefinition.DefaultExcludeHolidays
		_c.mutation.SetExcludeHolidays(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := sladefinition.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := sladefinition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := sladefinition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SLADefinitionCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SLADefinition.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sladefinition.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SLADefinition.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResponseTime(); !ok {
		return &ValidationError{Name: "response_time", err: errors.New(`ent: missing required field "SLADefinition.response_time"`)}
	}
	if v, ok := _c.mutation.ResponseTime(); ok {
		if err := sladefinition.ResponseTimeValidator(v); err != nil {
			return &ValidationError{Name: "response_time", err: fmt.Errorf(`ent: validator failed for field "SLADefinition.response_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResolutionTime(); !ok {
		return &ValidationError{Name: "resolution_time", err: errors.New(`ent: missing required field "SLADefinition.resolution_time"`)}
	}
	if v, ok := _c.mutation.ResolutionTime(); ok {
		if err := sladefinition.ResolutionTimeValidator(v); err != nil {
			return &ValidationError{Name: "resolution_time", err: fmt.Errorf(`ent: validator failed for field "SLADefinition.resolution_time": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExcludeWeekends(); !ok {
		return &ValidationError{Name: "exclude_weekends", err: errors.New(`ent: missing required field "SLADefinition.exclude_weekends"`)}
	}
	if _, ok := _c.mutation.ExcludeHolidays(); !ok {
		return &ValidationError{Name: "exclude_holidays", err: errors.New(`ent: missing required field "SLADefinition.exclude_holidays"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "SLADefinition.is_active"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SLADefinition.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := sladefinition.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SLADefinition.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SLADefinition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SLADefinition.updated_at"`)}
	}
	return nil
}

func (_c *SLADefinitionCreate) sqlSave(ctx context.Context) (*SLADefinition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SLADefinitionCreate) createSpec() (*SLADefinition, *sqlgraph.CreateSpec) {
	var (
		_node = &SLADefinition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sladefinition.Table, sqlgraph.NewFieldSpec(sladefinition.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sladefinition.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(sladefinition.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ServiceType(); ok {
		_spec.SetField(sladefinition.FieldServiceType, field.TypeString, value)
		_node.ServiceType = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(sladefinition.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CategoryIds(); ok {
		_spec.SetField(sladefinition.FieldCategoryIds, field.TypeJSON, value)
		_node.CategoryIds = value
	}
	if value, ok := _c.mutation.ResponseTime(); ok {
		_spec.SetField(sladefinition.FieldResponseTime, field.TypeInt, value)
		_node.ResponseTime = value
	}
	if value, ok := _c.mutation.ResolutionTime(); ok {
		_spec.SetField(sladefinition.FieldResolutionTime, field.TypeInt, value)
		_node.ResolutionTime = value
	}
	if value, ok := _c.mutation.BusinessHours(); ok {
		_spec.SetField(sladefinition.FieldBusinessHours, field.TypeJSON, value)
		_node.BusinessHours = value
	}
	if value, ok := _c.mutation.EscalationRules(); ok {
		_spec.SetField(sladefinition.FieldEscalationRules, field.TypeJSON, value)
		_node.EscalationRules = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(sladefinition.FieldConditions, field.TypeJSON, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.ExcludeWeekends(); ok {
		_spec.SetField(sladefinition.FieldExcludeWeekends, field.TypeBool, value)
		_node.ExcludeWeekends = value
	}
	if value, ok := _c.mutation.ExcludeHolidays(); ok {
		_spec.SetField(sladefinition.FieldExcludeHolidays, field.TypeBool, value)
		_node.ExcludeHolidays = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(sladefinition.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(sladefinition.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sladefinition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sladefinition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ViolationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sladefinition.ViolationsTable,
			Columns: []string{sladefinition.ViolationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(slaviolation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MetricsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sladefinition.MetricsTable,
			Columns: []string{sladefinition.MetricsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(slametric.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sladefinition.TicketsTable,
			Columns: []string{sladefinition.TicketsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlertRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   sladefinition.AlertRulesTable,
			Columns: []string{sladefinition.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(slaalertrule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SLADefinition.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SLADefinitionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SLADefinitionCreate) OnConflict(opts ...sql.ConflictOption) *SLADefinitionUpsertOne {
	_c.conflict = opts
	return &SLADefinitionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SLADefinitionCreate) OnConflictColumns(columns ...string) *SLADefinitionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SLADefinitionUpsertOne{
		create: _c,
	}
}

type (
	// SLADefinitionUpsertOne is the builder for "upsert"-ing
	//  one SLADefinition node.
	SLADefinitionUpsertOne struct {
		create *SLADefinitionCreate
	}

	// SLADefinitionUpsert is the "OnConflict" setter.
	SLADefinitionUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *SLADefinitionUpsert) SetName(v string) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateName() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *SLADefinitionUpsert) SetDescription(v string) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateDescription() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SLADefinitionUpsert) ClearDescription() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldDescription)
	return u
}

// SetServiceType sets the "service_type" field.
func (u *SLADefinitionUpsert) SetServiceType(v string) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldServiceType, v)
	return u
}

// UpdateServiceType sets the "service_type" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateServiceType() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldServiceType)
	return u
}

// ClearServiceType clears the value of the "service_type" field.
func (u *SLADefinitionUpsert) ClearServiceType() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldServiceType)
	return u
}

// SetPriority sets the "priority" field.
func (u *SLADefinitionUpsert) SetPriority(v string) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdatePriority() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldPriority)
	return u
}

// ClearPriority clears the value of the "priority" field.
func (u *SLADefinitionUpsert) ClearPriority() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldPriority)
	return u
}

// SetCategoryIds sets the "category_ids" field.
func (u *SLADefinitionUpsert) SetCategoryIds(v []int) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldCategoryIds, v)
	return u
}

// UpdateCategoryIds sets the "category_ids" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateCategoryIds() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldCategoryIds)
	return u
}

// ClearCategoryIds clears the value of the "category_ids" field.
func (u *SLADefinitionUpsert) ClearCategoryIds() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldCategoryIds)
	return u
}

// SetResponseTime sets the "response_time" field.
func (u *SLADefinitionUpsert) SetResponseTime(v int) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldResponseTime, v)
	return u
}

// UpdateResponseTime sets the "response_time" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateResponseTime() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldResponseTime)
	return u
}

// AddResponseTime adds v to the "response_time" field.
func (u *SLADefinitionUpsert) AddResponseTime(v int) *SLADefinitionUpsert {
	u.Add(sladefinition.FieldResponseTime, v)
	return u
}

// SetResolutionTime sets the "resolution_time" field.
func (u *SLADefinitionUpsert) SetResolutionTime(v int) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldResolutionTime, v)
	return u
}

// UpdateResolutionTime sets the "resolution_time" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateResolutionTime() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldResolutionTime)
	return u
}

// AddResolutionTime adds v to the "resolution_time" field.
func (u *SLADefinitionUpsert) AddResolutionTime(v int) *SLADefinitionUpsert {
	u.Add(sladefinition.FieldResolutionTime, v)
	return u
}

// SetBusinessHours sets the "business_hours" field.
func (u *SLADefinitionUpsert) SetBusinessHours(v map[string]interface{}) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldBusinessHours, v)
	return u
}

// UpdateBusinessHours sets the "business_hours" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateBusinessHours() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldBusinessHours)
	return u
}

// ClearBusinessHours clears the value of the "business_hours" field.
func (u *SLADefinitionUpsert) ClearBusinessHours() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldBusinessHours)
	return u
}

// SetEscalationRules sets the "escalation_rules" field.
func (u *SLADefinitionUpsert) SetEscalationRules(v map[string]interface{}) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldEscalationRules, v)
	return u
}

// UpdateEscalationRules sets the "escalation_rules" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateEscalationRules() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldEscalationRules)
	return u
}

// ClearEscalationRules clears the value of the "escalation_rules" field.
func (u *SLADefinitionUpsert) ClearEscalationRules() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldEscalationRules)
	return u
}

// SetConditions sets the "conditions" field.
func (u *SLADefinitionUpsert) SetConditions(v map[string]interface{}) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldConditions, v)
	return u
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateConditions() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldConditions)
	return u
}

// ClearConditions clears the value of the "conditions" field.
func (u *SLADefinitionUpsert) ClearConditions() *SLADefinitionUpsert {
	u.SetNull(sladefinition.FieldConditions)
	return u
}

// SetExcludeWeekends sets the "exclude_weekends" field.
func (u *SLADefinitionUpsert) SetExcludeWeekends(v bool) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldExcludeWeekends, v)
	return u
}

// UpdateExcludeWeekends sets the "exclude_weekends" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateExcludeWeekends() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldExcludeWeekends)
	return u
}

// SetExcludeHolidays sets the "exclude_holidays" field.
func (u *SLADefinitionUpsert) SetExcludeHolidays(v bool) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldExcludeHolidays, v)
	return u
}

// UpdateExcludeHolidays sets the "exclude_holidays" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateExcludeHolidays() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldExcludeHolidays)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *SLADefinitionUpsert) SetIsActive(v bool) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateIsActive() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldIsActive)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *SLADefinitionUpsert) SetTenantID(v int) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateTenantID() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SLADefinitionUpsert) AddTenantID(v int) *SLADefinitionUpsert {
	u.Add(sladefinition.FieldTenantID, v)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *SLADefinitionUpsert) SetCreatedAt(v time.Time) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateCreatedAt() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SLADefinitionUpsert) SetUpdatedAt(v time.Time) *SLADefinitionUpsert {
	u.Set(sladefinition.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SLADefinitionUpsert) UpdateUpdatedAt() *SLADefinitionUpsert {
	u.SetExcluded(sladefinition.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SLADefinitionUpsertOne) UpdateNewValues() *SLADefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SLADefinitionUpsertOne) Ignore() *SLADefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SLADefinitionUpsertOne) DoNothing() *SLADefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SLADefinitionCreate.OnConflict
// documentation for more info.
func (u *SLADefinitionUpsertOne) Update(set func(*SLADefinitionUpsert)) *SLADefinitionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SLADefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SLADefinitionUpsertOne) SetName(v string) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateName() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SLADefinitionUpsertOne) SetDescription(v string) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateDescription() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SLADefinitionUpsertOne) ClearDescription() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetServiceType sets the "service_type" field.
func (u *SLADefinitionUpsertOne) SetServiceType(v string) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetServiceType(v)
	})
}

// UpdateServiceType sets the "service_type" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateServiceType() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateServiceType()
	})
}

// ClearServiceType clears the value of the "service_type" field.
func (u *SLADefinitionUpsertOne) ClearServiceType() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearServiceType()
	})
}

// SetPriority sets the "priority" field.
func (u *SLADefinitionUpsertOne) SetPriority(v string) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdatePriority() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdatePriority()
	})
}

// ClearPriority clears the value of the "priority" field.
func (u *SLADefinitionUpsertOne) ClearPriority() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearPriority()
	})
}

// SetCategoryIds sets the "category_ids" field.
func (u *SLADefinitionUpsertOne) SetCategoryIds(v []int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetCategoryIds(v)
	})
}

// UpdateCategoryIds sets the "category_ids" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateCategoryIds() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateCategoryIds()
	})
}

// ClearCategoryIds clears the value of the "category_ids" field.
func (u *SLADefinitionUpsertOne) ClearCategoryIds() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearCategoryIds()
	})
}

// SetResponseTime sets the "response_time" field.
func (u *SLADefinitionUpsertOne) SetResponseTime(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetResponseTime(v)
	})
}

// AddResponseTime adds v to the "response_time" field.
func (u *SLADefinitionUpsertOne) AddResponseTime(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddResponseTime(v)
	})
}

// UpdateResponseTime sets the "response_time" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateResponseTime() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateResponseTime()
	})
}

// SetResolutionTime sets the "resolution_time" field.
func (u *SLADefinitionUpsertOne) SetResolutionTime(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetResolutionTime(v)
	})
}

// AddResolutionTime adds v to the "resolution_time" field.
func (u *SLADefinitionUpsertOne) AddResolutionTime(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddResolutionTime(v)
	})
}

// UpdateResolutionTime sets the "resolution_time" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateResolutionTime() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateResolutionTime()
	})
}

// SetBusinessHours sets the "business_hours" field.
func (u *SLADefinitionUpsertOne) SetBusinessHours(v map[string]interface{}) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetBusinessHours(v)
	})
}

// UpdateBusinessHours sets the "business_hours" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateBusinessHours() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateBusinessHours()
	})
}

// ClearBusinessHours clears the value of the "business_hours" field.
func (u *SLADefinitionUpsertOne) ClearBusinessHours() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearBusinessHours()
	})
}

// SetEscalationRules sets the "escalation_rules" field.
func (u *SLADefinitionUpsertOne) SetEscalationRules(v map[string]interface{}) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetEscalationRules(v)
	})
}

// UpdateEscalationRules sets the "escalation_rules" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateEscalationRules() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateEscalationRules()
	})
}

// ClearEscalationRules clears the value of the "escalation_rules" field.
func (u *SLADefinitionUpsertOne) ClearEscalationRules() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearEscalationRules()
	})
}

// SetConditions sets the "conditions" field.
func (u *SLADefinitionUpsertOne) SetConditions(v map[string]interface{}) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateConditions() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *SLADefinitionUpsertOne) ClearConditions() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearConditions()
	})
}

// SetExcludeWeekends sets the "exclude_weekends" field.
func (u *SLADefinitionUpsertOne) SetExcludeWeekends(v bool) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetExcludeWeekends(v)
	})
}

// UpdateExcludeWeekends sets the "exclude_weekends" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateExcludeWeekends() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateExcludeWeekends()
	})
}

// SetExcludeHolidays sets the "exclude_holidays" field.
func (u *SLADefinitionUpsertOne) SetExcludeHolidays(v bool) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetExcludeHolidays(v)
	})
}

// UpdateExcludeHolidays sets the "exclude_holidays" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateExcludeHolidays() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateExcludeHolidays()
	})
}

// SetIsActive sets the "is_active" field.
func (u *SLADefinitionUpsertOne) SetIsActive(v bool) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateIsActive() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateIsActive()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *SLADefinitionUpsertOne) SetTenantID(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SLADefinitionUpsertOne) AddTenantID(v int) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateTenantID() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateTenantID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SLADefinitionUpsertOne) SetCreatedAt(v time.Time) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateCreatedAt() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SLADefinitionUpsertOne) SetUpdatedAt(v time.Time) *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SLADefinitionUpsertOne) UpdateUpdatedAt() *SLADefinitionUpsertOne {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SLADefinitionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SLADefinitionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SLADefinitionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SLADefinitionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SLADefinitionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SLADefinitionCreateBulk is the builder for creating many SLADefinition entities in bulk.
type SLADefinitionCreateBulk struct {
	config
	err      error
	builders []*SLADefinitionCreate
	conflict []sql.ConflictOption
}

// Save creates the SLADefinition entities in the database.
func (_c *SLADefinitionCreateBulk) Save(ctx context.Context) ([]*SLADefinition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SLADefinition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SLADefinitionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SLADefinitionCreateBulk) SaveX(ctx context.Context) []*SLADefinition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SLADefinitionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SLADefinitionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SLADefinition.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SLADefinitionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *SLADefinitionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SLADefinitionUpsertBulk {
	_c.conflict = opts
	return &SLADefinitionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SLADefinitionCreateBulk) OnConflictColumns(columns ...string) *SLADefinitionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SLADefinitionUpsertBulk{
		create: _c,
	}
}

// SLADefinitionUpsertBulk is the builder for "upsert"-ing
// a bulk of SLADefinition nodes.
type SLADefinitionUpsertBulk struct {
	create *SLADefinitionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SLADefinitionUpsertBulk) UpdateNewValues() *SLADefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SLADefinition.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SLADefinitionUpsertBulk) Ignore() *SLADefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SLADefinitionUpsertBulk) DoNothing() *SLADefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SLADefinitionCreateBulk.OnConflict
// documentation for more info.
func (u *SLADefinitionUpsertBulk) Update(set func(*SLADefinitionUpsert)) *SLADefinitionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SLADefinitionUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *SLADefinitionUpsertBulk) SetName(v string) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateName() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *SLADefinitionUpsertBulk) SetDescription(v string) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateDescription() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SLADefinitionUpsertBulk) ClearDescription() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearDescription()
	})
}

// SetServiceType sets the "service_type" field.
func (u *SLADefinitionUpsertBulk) SetServiceType(v string) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetServiceType(v)
	})
}

// UpdateServiceType sets the "service_type" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateServiceType() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateServiceType()
	})
}

// ClearServiceType clears the value of the "service_type" field.
func (u *SLADefinitionUpsertBulk) ClearServiceType() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearServiceType()
	})
}

// SetPriority sets the "priority" field.
func (u *SLADefinitionUpsertBulk) SetPriority(v string) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdatePriority() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdatePriority()
	})
}

// ClearPriority clears the value of the "priority" field.
func (u *SLADefinitionUpsertBulk) ClearPriority() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearPriority()
	})
}

// SetCategoryIds sets the "category_ids" field.
func (u *SLADefinitionUpsertBulk) SetCategoryIds(v []int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetCategoryIds(v)
	})
}

// UpdateCategoryIds sets the "category_ids" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateCategoryIds() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateCategoryIds()
	})
}

// ClearCategoryIds clears the value of the "category_ids" field.
func (u *SLADefinitionUpsertBulk) ClearCategoryIds() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearCategoryIds()
	})
}

// SetResponseTime sets the "response_time" field.
func (u *SLADefinitionUpsertBulk) SetResponseTime(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetResponseTime(v)
	})
}

// AddResponseTime adds v to the "response_time" field.
func (u *SLADefinitionUpsertBulk) AddResponseTime(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddResponseTime(v)
	})
}

// UpdateResponseTime sets the "response_time" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateResponseTime() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateResponseTime()
	})
}

// SetResolutionTime sets the "resolution_time" field.
func (u *SLADefinitionUpsertBulk) SetResolutionTime(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetResolutionTime(v)
	})
}

// AddResolutionTime adds v to the "resolution_time" field.
func (u *SLADefinitionUpsertBulk) AddResolutionTime(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddResolutionTime(v)
	})
}

// UpdateResolutionTime sets the "resolution_time" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateResolutionTime() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateResolutionTime()
	})
}

// SetBusinessHours sets the "business_hours" field.
func (u *SLADefinitionUpsertBulk) SetBusinessHours(v map[string]interface{}) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetBusinessHours(v)
	})
}

// UpdateBusinessHours sets the "business_hours" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateBusinessHours() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateBusinessHours()
	})
}

// ClearBusinessHours clears the value of the "business_hours" field.
func (u *SLADefinitionUpsertBulk) ClearBusinessHours() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearBusinessHours()
	})
}

// SetEscalationRules sets the "escalation_rules" field.
func (u *SLADefinitionUpsertBulk) SetEscalationRules(v map[string]interface{}) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetEscalationRules(v)
	})
}

// UpdateEscalationRules sets the "escalation_rules" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateEscalationRules() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateEscalationRules()
	})
}

// ClearEscalationRules clears the value of the "escalation_rules" field.
func (u *SLADefinitionUpsertBulk) ClearEscalationRules() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearEscalationRules()
	})
}

// SetConditions sets the "conditions" field.
func (u *SLADefinitionUpsertBulk) SetConditions(v map[string]interface{}) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetConditions(v)
	})
}

// UpdateConditions sets the "conditions" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateConditions() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateConditions()
	})
}

// ClearConditions clears the value of the "conditions" field.
func (u *SLADefinitionUpsertBulk) ClearConditions() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.ClearConditions()
	})
}

// SetExcludeWeekends sets the "exclude_weekends" field.
func (u *SLADefinitionUpsertBulk) SetExcludeWeekends(v bool) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetExcludeWeekends(v)
	})
}

// UpdateExcludeWeekends sets the "exclude_weekends" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateExcludeWeekends() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateExcludeWeekends()
	})
}

// SetExcludeHolidays sets the "exclude_holidays" field.
func (u *SLADefinitionUpsertBulk) SetExcludeHolidays(v bool) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetExcludeHolidays(v)
	})
}

// UpdateExcludeHolidays sets the "exclude_holidays" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateExcludeHolidays() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateExcludeHolidays()
	})
}

// SetIsActive sets the "is_active" field.
func (u *SLADefinitionUpsertBulk) SetIsActive(v bool) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateIsActive() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateIsActive()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *SLADefinitionUpsertBulk) SetTenantID(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SLADefinitionUpsertBulk) AddTenantID(v int) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateTenantID() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateTenantID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *SLADefinitionUpsertBulk) SetCreatedAt(v time.Time) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateCreatedAt() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SLADefinitionUpsertBulk) SetUpdatedAt(v time.Time) *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SLADefinitionUpsertBulk) UpdateUpdatedAt() *SLADefinitionUpsertBulk {
	return u.Update(func(s *SLADefinitionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SLADefinitionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SLADefinitionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SLADefinitionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SLADefinitionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
