// Code generated by ent, DO NOT EDIT.

package workitemnumbersequence

import (
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldTenantID, v))
}

// Period applies equality check predicate on the "period" field. It's identical to PeriodEQ.
func Period(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldPeriod, v))
}

// LastValue applies equality check predicate on the "last_value" field. It's identical to LastValueEQ.
func LastValue(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldLastValue, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldTenantID, v))
}

// PeriodEQ applies the EQ predicate on the "period" field.
func PeriodEQ(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldPeriod, v))
}

// PeriodNEQ applies the NEQ predicate on the "period" field.
func PeriodNEQ(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldPeriod, v))
}

// PeriodIn applies the In predicate on the "period" field.
func PeriodIn(vs ...string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldPeriod, vs...))
}

// PeriodNotIn applies the NotIn predicate on the "period" field.
func PeriodNotIn(vs ...string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldPeriod, vs...))
}

// PeriodGT applies the GT predicate on the "period" field.
func PeriodGT(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldPeriod, v))
}

// PeriodGTE applies the GTE predicate on the "period" field.
func PeriodGTE(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldPeriod, v))
}

// PeriodLT applies the LT predicate on the "period" field.
func PeriodLT(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldPeriod, v))
}

// PeriodLTE applies the LTE predicate on the "period" field.
func PeriodLTE(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldPeriod, v))
}

// PeriodContains applies the Contains predicate on the "period" field.
func PeriodContains(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldContains(FieldPeriod, v))
}

// PeriodHasPrefix applies the HasPrefix predicate on the "period" field.
func PeriodHasPrefix(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldHasPrefix(FieldPeriod, v))
}

// PeriodHasSuffix applies the HasSuffix predicate on the "period" field.
func PeriodHasSuffix(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldHasSuffix(FieldPeriod, v))
}

// PeriodEqualFold applies the EqualFold predicate on the "period" field.
func PeriodEqualFold(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEqualFold(FieldPeriod, v))
}

// PeriodContainsFold applies the ContainsFold predicate on the "period" field.
func PeriodContainsFold(v string) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldContainsFold(FieldPeriod, v))
}

// LastValueEQ applies the EQ predicate on the "last_value" field.
func LastValueEQ(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldLastValue, v))
}

// LastValueNEQ applies the NEQ predicate on the "last_value" field.
func LastValueNEQ(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldLastValue, v))
}

// LastValueIn applies the In predicate on the "last_value" field.
func LastValueIn(vs ...int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldLastValue, vs...))
}

// LastValueNotIn applies the NotIn predicate on the "last_value" field.
func LastValueNotIn(vs ...int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldLastValue, vs...))
}

// LastValueGT applies the GT predicate on the "last_value" field.
func LastValueGT(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldLastValue, v))
}

// LastValueGTE applies the GTE predicate on the "last_value" field.
func LastValueGTE(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldLastValue, v))
}

// LastValueLT applies the LT predicate on the "last_value" field.
func LastValueLT(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldLastValue, v))
}

// LastValueLTE applies the LTE predicate on the "last_value" field.
func LastValueLTE(v int64) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldLastValue, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkItemNumberSequence) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkItemNumberSequence) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkItemNumberSequence) predicate.WorkItemNumberSequence {
	return predicate.WorkItemNumberSequence(sql.NotPredicates(p))
}
