// Code generated by ent, DO NOT EDIT.

package incidentruleactionreceipt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the incidentruleactionreceipt type in the database.
	Label = "incident_rule_action_receipt"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldExecutionID holds the string denoting the execution_id field in the database.
	FieldExecutionID = "execution_id"
	// FieldActionIndex holds the string denoting the action_index field in the database.
	FieldActionIndex = "action_index"
	// FieldCompletedAt holds the string denoting the completed_at field in the database.
	FieldCompletedAt = "completed_at"
	// EdgeExecution holds the string denoting the execution edge name in mutations.
	EdgeExecution = "execution"
	// Table holds the table name of the incidentruleactionreceipt in the database.
	Table = "incident_rule_action_receipts"
	// ExecutionTable is the table that holds the execution relation/edge.
	ExecutionTable = "incident_rule_action_receipts"
	// ExecutionInverseTable is the table name for the IncidentRuleExecution entity.
	// It exists in this package in order to avoid circular dependency with the "incidentruleexecution" package.
	ExecutionInverseTable = "incident_rule_executions"
	// ExecutionColumn is the table column denoting the execution relation/edge.
	ExecutionColumn = "execution_id"
)

// Columns holds all SQL columns for incidentruleactionreceipt fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldExecutionID,
	FieldActionIndex,
	FieldCompletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(int) error
	// ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	ExecutionIDValidator func(int) error
	// ActionIndexValidator is a validator for the "action_index" field. It is called by the builders before save.
	ActionIndexValidator func(int) error
	// DefaultCompletedAt holds the default value on creation for the "completed_at" field.
	DefaultCompletedAt func() time.Time
)

// OrderOption defines the ordering options for the IncidentRuleActionReceipt queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByExecutionID orders the results by the execution_id field.
func ByExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionID, opts...).ToFunc()
}

// ByActionIndex orders the results by the action_index field.
func ByActionIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActionIndex, opts...).ToFunc()
}

// ByCompletedAt orders the results by the completed_at field.
func ByCompletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedAt, opts...).ToFunc()
}

// ByExecutionField orders the results by execution field.
func ByExecutionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionStep(), sql.OrderByField(field, opts...))
	}
}
func newExecutionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExecutionTable, ExecutionColumn),
	)
}
