
DO $verify$
BEGIN
 IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=current_schema() AND table_name='service_requests' AND column_name=ANY(ARRAY['tenant_id','requester_id','processor_id','version','created_at','updated_at','deleted_at'])) THEN RAISE EXCEPTION 'ServiceRequest shared columns must be absent'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid='service_requests'::regclass AND attname='ticket_id' AND attnotnull AND NOT attisdropped) THEN RAISE EXCEPTION 'ServiceRequest WorkItem must be required'; END IF;
 IF (SELECT count(*) FROM pg_constraint c JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=c.conkey[1] WHERE c.conrelid='service_requests'::regclass AND c.contype='f' AND a.attname='ticket_id') <> 1 OR NOT EXISTS(SELECT 1 FROM pg_constraint c JOIN pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=c.conkey[1] JOIN pg_attribute b ON b.attrelid=c.confrelid AND b.attnum=c.confkey[1] WHERE c.conrelid='service_requests'::regclass AND c.confrelid='tickets'::regclass AND c.conname='service_requests_work_item_fk' AND c.contype='f' AND c.convalidated AND NOT c.condeferrable AND cardinality(c.conkey)=1 AND cardinality(c.confkey)=1 AND a.attname='ticket_id' AND b.attname='id' AND c.confdeltype='a' AND c.confupdtype='a') THEN RAISE EXCEPTION 'ServiceRequest WorkItem foreign key must be exact'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_index i JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=i.indkey[0] WHERE i.indrelid='service_requests'::regclass AND i.indisunique AND i.indisvalid AND i.indisready AND i.indnkeyatts=1 AND i.indnatts=1 AND i.indpred IS NULL AND i.indexprs IS NULL AND a.attname='ticket_id') THEN RAISE EXCEPTION 'ServiceRequest WorkItem must be unique'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_class WHERE oid='service_requests'::regclass AND relrowsecurity AND relforcerowsecurity) OR (SELECT count(*) FROM pg_policy WHERE polrelid='service_requests'::regclass) <> 1 THEN RAISE EXCEPTION 'ServiceRequest RLS must be enforced'; END IF;
END $verify$;
