// Code generated by ent, DO NOT EDIT.

package connectorconfig

import (
	"itsm-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldTenantID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldName, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldProvider, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldEnabled, v))
}

// Credentials applies equality check predicate on the "credentials" field. It's identical to CredentialsEQ.
func Credentials(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldCredentials, v))
}

// Settings applies equality check predicate on the "settings" field. It's identical to SettingsEQ.
func Settings(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldSettings, v))
}

// Labels applies equality check predicate on the "labels" field. It's identical to LabelsEQ.
func Labels(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldLabels, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldTenantID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContainsFold(FieldName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContainsFold(FieldProvider, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldEnabled, v))
}

// CredentialsEQ applies the EQ predicate on the "credentials" field.
func CredentialsEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldCredentials, v))
}

// CredentialsNEQ applies the NEQ predicate on the "credentials" field.
func CredentialsNEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldCredentials, v))
}

// CredentialsIn applies the In predicate on the "credentials" field.
func CredentialsIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldCredentials, vs...))
}

// CredentialsNotIn applies the NotIn predicate on the "credentials" field.
func CredentialsNotIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldCredentials, vs...))
}

// CredentialsGT applies the GT predicate on the "credentials" field.
func CredentialsGT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldCredentials, v))
}

// CredentialsGTE applies the GTE predicate on the "credentials" field.
func CredentialsGTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldCredentials, v))
}

// CredentialsLT applies the LT predicate on the "credentials" field.
func CredentialsLT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldCredentials, v))
}

// CredentialsLTE applies the LTE predicate on the "credentials" field.
func CredentialsLTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldCredentials, v))
}

// CredentialsContains applies the Contains predicate on the "credentials" field.
func CredentialsContains(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContains(FieldCredentials, v))
}

// CredentialsHasPrefix applies the HasPrefix predicate on the "credentials" field.
func CredentialsHasPrefix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasPrefix(FieldCredentials, v))
}

// CredentialsHasSuffix applies the HasSuffix predicate on the "credentials" field.
func CredentialsHasSuffix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasSuffix(FieldCredentials, v))
}

// CredentialsIsNil applies the IsNil predicate on the "credentials" field.
func CredentialsIsNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIsNull(FieldCredentials))
}

// CredentialsNotNil applies the NotNil predicate on the "credentials" field.
func CredentialsNotNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotNull(FieldCredentials))
}

// CredentialsEqualFold applies the EqualFold predicate on the "credentials" field.
func CredentialsEqualFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEqualFold(FieldCredentials, v))
}

// CredentialsContainsFold applies the ContainsFold predicate on the "credentials" field.
func CredentialsContainsFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContainsFold(FieldCredentials, v))
}

// SettingsEQ applies the EQ predicate on the "settings" field.
func SettingsEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldSettings, v))
}

// SettingsNEQ applies the NEQ predicate on the "settings" field.
func SettingsNEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldSettings, v))
}

// SettingsIn applies the In predicate on the "settings" field.
func SettingsIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldSettings, vs...))
}

// SettingsNotIn applies the NotIn predicate on the "settings" field.
func SettingsNotIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldSettings, vs...))
}

// SettingsGT applies the GT predicate on the "settings" field.
func SettingsGT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldSettings, v))
}

// SettingsGTE applies the GTE predicate on the "settings" field.
func SettingsGTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldSettings, v))
}

// SettingsLT applies the LT predicate on the "settings" field.
func SettingsLT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldSettings, v))
}

// SettingsLTE applies the LTE predicate on the "settings" field.
func SettingsLTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldSettings, v))
}

// SettingsContains applies the Contains predicate on the "settings" field.
func SettingsContains(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContains(FieldSettings, v))
}

// SettingsHasPrefix applies the HasPrefix predicate on the "settings" field.
func SettingsHasPrefix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasPrefix(FieldSettings, v))
}

// SettingsHasSuffix applies the HasSuffix predicate on the "settings" field.
func SettingsHasSuffix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasSuffix(FieldSettings, v))
}

// SettingsIsNil applies the IsNil predicate on the "settings" field.
func SettingsIsNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIsNull(FieldSettings))
}

// SettingsNotNil applies the NotNil predicate on the "settings" field.
func SettingsNotNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotNull(FieldSettings))
}

// SettingsEqualFold applies the EqualFold predicate on the "settings" field.
func SettingsEqualFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEqualFold(FieldSettings, v))
}

// SettingsContainsFold applies the ContainsFold predicate on the "settings" field.
func SettingsContainsFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContainsFold(FieldSettings, v))
}

// LabelsEQ applies the EQ predicate on the "labels" field.
func LabelsEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldLabels, v))
}

// LabelsNEQ applies the NEQ predicate on the "labels" field.
func LabelsNEQ(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldLabels, v))
}

// LabelsIn applies the In predicate on the "labels" field.
func LabelsIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldLabels, vs...))
}

// LabelsNotIn applies the NotIn predicate on the "labels" field.
func LabelsNotIn(vs ...string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldLabels, vs...))
}

// LabelsGT applies the GT predicate on the "labels" field.
func LabelsGT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldLabels, v))
}

// LabelsGTE applies the GTE predicate on the "labels" field.
func LabelsGTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldLabels, v))
}

// LabelsLT applies the LT predicate on the "labels" field.
func LabelsLT(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldLabels, v))
}

// LabelsLTE applies the LTE predicate on the "labels" field.
func LabelsLTE(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldLabels, v))
}

// LabelsContains applies the Contains predicate on the "labels" field.
func LabelsContains(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContains(FieldLabels, v))
}

// LabelsHasPrefix applies the HasPrefix predicate on the "labels" field.
func LabelsHasPrefix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasPrefix(FieldLabels, v))
}

// LabelsHasSuffix applies the HasSuffix predicate on the "labels" field.
func LabelsHasSuffix(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldHasSuffix(FieldLabels, v))
}

// LabelsIsNil applies the IsNil predicate on the "labels" field.
func LabelsIsNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIsNull(FieldLabels))
}

// LabelsNotNil applies the NotNil predicate on the "labels" field.
func LabelsNotNil() predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotNull(FieldLabels))
}

// LabelsEqualFold applies the EqualFold predicate on the "labels" field.
func LabelsEqualFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEqualFold(FieldLabels, v))
}

// LabelsContainsFold applies the ContainsFold predicate on the "labels" field.
func LabelsContainsFold(v string) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldContainsFold(FieldLabels, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ConnectorConfig) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ConnectorConfig) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ConnectorConfig) predicate.ConnectorConfig {
	return predicate.ConnectorConfig(sql.NotPredicates(p))
}
